### ISSUE TITLE
オープンソースの文書入力・校正システムを作る件について

### ISSUE THREAD

**Issue by key-amb** [aozorahack/aozorahack#1]
昨日のアイデアソン、お疲れ様でした。
正直進め方もまだ戸惑っている(たぶんそんなにはっきり決まっているわけではないと思う)ところですが、叩き台も必要だろうということで、手始めに1つ Issue を登録しておきます。

アイデアソンでもいくつか同じようなアイディアが出ましたが、掲題の文書入力・校正システムをこの Organization の下で作るのはいいのではないかな、と思っています。
まずは賛成・反対を伺いたいです。
## 前提
- OSS として MIT などのライセンスで作る
- システムの完成イメージはだいたいこんな感じ: [(インフラ分科会) 入力・校正支援システム](http://www.slideshare.net/YasutakeKiyoshi/aozorahack)
- 青空文庫の文書フォーマットやワークフローに特化した形で作るか、一般的な文書(雑誌・組織)の入力・校正作業にも使えるものを作るかは、議論の余地があると思っています。
  - 後者の方が間口は広がる。
  - 後者を選ぶにしても、青空文庫への対応は必須で、優先されるべきでしょう。
  - 私はなるべく後者がいいかなと思っていて、どうしても難しい部分があれば前者にスイッチするという方針でいいのではないかなと思っています。
- そこそこ複雑で大きなシステムになると思うので、やるとしたらこのシステム単体でもちゃんと設計して仕様を決めて…とやっていったほうがよさそう。
## お願いしたいこと
- 賛成 :+1: or 反対 :-1: を伺いたいです。
  - わざわざ反対を押す人はそんなにいないとは思うのですが、逆に根拠のある批判・指摘は参考にしたいと思います。
- やるなら開発に協力してもいいという場合はお知らせ頂きたいです。自分1人では絶対無理。
- そもそも前提に付け加えてほしいところや、変えてほしいところなどあればご意見下さい。
- 前提を更に掘り下げて、具体的な設計・実装について考えるのは、やると決まった後でもいいと思いますが、「自分だったらこうしたい」とか「こんな感じで作ったらいいんじゃないか」みたいな意見も歓迎します！

以上、よろしくお願いします。
## 参考
- [「Code for 青空文庫」アイデアソン #1 : ATND](https://atnd.org/events/66230)
- [青空文庫を救え！「Code for 青空文庫」アイデアソン #1 レポート #aozorahack:見て歩く者 by 鷹野凌](http://www.wildhawkfield.com/2015/05/save-the-aozora-library.html)

**Comment by takahashim** [comment]
:+1:
何もないところからスタートして、実際に使えるプロダクトを作るのは案外難しそうな気もしますが、まずはやってみるのがよいのではないでしょうか。
希望のリポジトリ名を教えていただければ作成します。

**Comment by key-amb** [comment]
ありがとうございます！
とりあえず GitLab 持ってきたらプロトタイプとしては使えるんじゃないかな〜と思ってたりします。MIT License のようですし。

名前・・・そういえば考えてなかった。
ちょっと考えます！

**Comment by kskktk** [comment]
:+1: お手伝いできることがあればお手伝いします！

**Comment by ksato9700** [comment]
:thumbsup:
silicagelとしてkey-ambさんのチームに参加させてもらった者です。せっかくアイディア出ししたので実現まで持って行きたいですよね。出来る範囲でお手伝いします！

仰るように、全部つくろうとするとそれなりに規模が大きくなるので何かしら設計が必要と思います。まずはMinimum Viable Productが何かを見定めるところからですかね...

**Comment by bsbakery** [comment]
:+1:
こちらこそよろしくお願いいたします！　何か必要なものがあったらおっしゃってください！
とりあえず役立ちそうなサイト内の参照ページを示しておきますね。
[「青空文庫ＦＡＱ：入力・校正について」](http://www.aozora.gr.jp/guide/aozora_bunko_faq.html#midashi580)

**Comment by ksato9700** [comment]
一人で勝手に先走りしてるかも知れませんが(^^;; 議論のネタとして少し考えたことを書いておきます。

何が一番のコアになる機能なのかをつらつらと考えてみると、やはり本文テキストデータのリポジトリなのではないかと思いました。

本文を格納した「Gitの様な」バージョン管理システムのリポジトリと、その利用ポリシーが、まずは最小限必要なモノなのではないかと。

ここで利用ポリシーと言っているのは、例えばコミットとブランチングのルールだったりします。公開されたバージョンはマスターブランチに置く、作業中のモノそれぞれブランチを切る、ブランチからそれが入力中なのか、校正中なのか、素読み中なのかわかる様にする、とかのルールです。

複数人同時入力とか、部分入力を可能にするとか幾つか要件があると思うので、それを洗い出した上でそういったルール作りをしていくというのでは如何でしょうか？

**Comment by cognitom** [comment]
おはようございます。アイデアソンには参加できなかったのですが、興味津々で見守っている者です。

@ksato9700 さん、裏側としてはGitがそのまま使えると思っているのですが、どうでしょうか? 「校正完了」「素読み完了」などはGitのタグが使える気がします。Webアプリ(or デスクトップアプリ)を作るにあたって、「利用ポリシー」に合わせてGitの**「ガワ」を被せるだけ**だと楽そうです。(=エンジニアは、素のGitにアクセスすればOK)

これなら最小ステップとして、「定型のGitコマンドをAtomエディタから呼び出せる様にする」とかでもなんとかなりそうです。一方で、 @key-amb さんの[スライド](http://www.slideshare.net/YasutakeKiyoshi/aozorahack)には、SNS的なアイデアも含まれているので、そちらは何か中央集権な仕組みも要ります。下記はあくまでも例ですが、何を中央に置いて、何を中央に置かなくて良いかも考えておきたいですね。
- **中央**に置くのは? : 例. 工作員名簿、実績、リポジトリへのリンク...etc
- **分散**してて良いのは? : 例. 各書籍のリポジトリ、入力・校正システム...etc

**Comment by key-amb** [comment]
アイディアありがとうございます！
自分も裏側は Git でいいかな、と思っていました。仕組みを知ってるエンジニアが多いですしね。

あまりまだ煮詰めてはなかったのですけど、自分は Web アプリにある程度機能を持たせる方向で考えていました。
が、Atom は既に Git に対応した機能がありますし、Atom(クライアント)側で頑張るというのも面白いアイディアだと思います。

早くリポジトリ作って要求整理、要件定義など進めていきたいですね。
名前考えますね。

**Comment by key-amb** [comment]
名前考えました。
1. Kosakuin ... 工作院。もちろん青空文庫で入力・校正する人が工作員と呼ばれることに由来。
2. Revisioner ... 改訂していく人。改訂者。

2番は一般的すぎるから、1番でいいんじゃないかなぁという気持ちになっているところです。

**Comment by ksato9700** [comment]
私もGitそのまま派なのですが、アイディアソンの時には、Git-likeな…という表現だったので(^^)   Gitであまり反論もなさそうなのでそれを軸に考えてみましょうか。

状態遷移に関しては、もちろんタグでも良いと思いますし、Git-flowみたいに状態ごとのブランチ作ってということも可能かと思います。解決策に飛びつく前にまずは要件整理して、解くべき問題をクリアにしてからかなと思います。

それから、名称の「工作院」は私も+1です。

**Comment by cognitom** [comment]
「工作院」 :+1:
複雑さがどこまで受け入れられるのかが肝ですね。(見かけ上)なるべく一本線に見せるなどの工夫は必要かもしれません。むしろ、Gitの機能をどれだけ制限するかという話になりそうな気もしつつ。

私も「解決策に飛びつく前にまずは要件整理」に賛成です。試しに、リポジトリを作って[工作員マニュアル](http://www.aozora.gr.jp/KOSAKU/MANU_IND.html)あたりを、写経(というかコピペ)して要件洗い出しとかどうでしょうか?

**Comment by takahashim** [comment]
ではkosakuin(全部小文字)でリポジトリを作成します。

**Comment by takahashim** [comment]
作成しました :tada:  https://github.com/aozorahack/kosakuin

また、kosakuinチームを作って、:+1: した人はみんなinviteしました。kosakuinリポジトリへのread/write accessが可能になります（あんまり権限ばらまかない方が良いような気もしますが、追加するのも面倒なのでこの辺の方針は流動的です）。

**Comment by takahashim** [comment]
というわけで続きは https://github.com/aozorahack/kosakuin でお願いします。こちらのissueは閉じておきますね。

**Comment by key-amb** [comment]
リポジトリ作成ありがとうございます！
あとは kosakuin 側で…と書こうとしたらもう閉じられてしまった。(さすが、速い。)
