### ISSUE TITLE
「ideathon」リポジトリ作成依頼

### ISSUE THREAD

**Issue by kskktk** [aozorahack/aozorahack#12]
事後承認をいただく形になって申し訳ありません。
下記を申請します。承認をお願いします。
- リポジトリ名(日本語)  : アイデアソン資料置き場
- リポジトリのパス名(URLに使うやつ） : aozorahack / ideathon （勇み足ですでに作成済）
- リポジトリの紹介文 : アイデアソンの成果資料（特にmdファイルで提出されたもの）を置き、いつでも参照できるようにする

**Comment by key-amb** [comment]
:+1:

**Comment by kskktk** [comment]
ありがとうございます！では本issueを閉じますね。ありがとうございます！
