### ISSUE TITLE
工作員作業マニュアルをaozorahackに

### ISSUE THREAD

**Issue by geohasegawa** [aozorahack/aozorahack#13]
先日のアイデアソンでオープン化の話が出てきていましたが、青空文庫のドキュメントもオープン化していきたいと考えております。
その中でも、青空文庫の工作員作業マニュアルは、これからシステム面での改良を加える上で色々参照することになると思いますし、場合によっては書き換えることもでてくると思います。

そこで、工作員作業マニュアルにCC BYライセンスをつけていただいて、こちらのaozorahackにもあげていただけないでしょうか。
aozorahackの方でも管理すれば、マニュアルの版の管理などもしやすくなると思います。

つきましては、大久保さんか野口さん、もしこちらを見ていらっしゃればご検討していただけると嬉しいです！

参考
- [工作員作業マニュアル](http://www.aozora.gr.jp/KOSAKU/MANU_MOKU.html)

**Comment by cognitom** [comment]
:+1:

**Comment by henoheno** [comment]
～ いましらべたあらすじ ～

「工作員作業マニュアル」は
(ネット的にはこちらが入口のようです http://www.aozora.gr.jp/KOSAKU/MANU_IND.html )
青空文庫のwebサイトにおいて「早わかり」「FAQ」「インデックス」等と分けて配置および管理されている ひとかたまり の著作物で、
「青空文庫」（reception at aozora.gr.jp）の名義で発表されています。
今現在は、これに対するライセンス（それを他者が取扱う際の約束事）は著作者から特に示されていません。良いとも悪いとも書かれていません。
PDF版が企画されていたくらいで、独立性の高い(他の著作物との結合度合が低い)著作物です。
一部「青空文庫呼びかけ人一同」名義の著作物も含まれています。

～～～～～～～～～～～～

どのようにご希望なのか次第ですが：

A.「コンテンツの保護ならびに運用の負担減」といった当初路線については
(そんな取扱いをする事について、著作者の同意が得られる前提で)
ほかの著作物と混ぜないよう区別しながらであれば、ライセンス適用の検討を待たずとも、ひとまずどこかに移植（最悪コピー）することが可能かと思います。
　・各自がどんな環境を作れば良いのか？
　・どうやって文書を更新するのか？
　・どうやって最新版を掲載（コンテンツを差し替え）するのか？
といった所を現実にするところまで済ませないと負担減にはなりませんから、
 aozorahack にコピーしてはどうか、というtagtaggerさん発案の企画は、今この瞬間においては試作・試行錯誤の始まりのような位置づけになるかと思います。

B. 「異なるライセンスの適用？や奥付表記の整理整頓再認識」については
著作物それぞれごとのご事情を踏まえつつ、まとめてお考えいただくことができますが、そもそもそこに価値を見出されるのかどうか、今後どのライセンスを望まれるのか、それをどこに、どこまで遡って適用するのかどうかについて、方向づけをいただく必要があります。
著名なライセンスを採用する効果としては、負担減ならびにスピードアップがあります。

他の著作物の状況の例：

青空文庫の提案 (すでにクリエイティブ・コモンズ「表示 2.1 日本」)
http://www.aozora.gr.jp/cards/001790/files/56572_51810.html

早わかりとFAQ(「制作にあたったのは、ボランティアの皆さんです。」)
http://www.aozora.gr.jp/guide/aozora_bunko_hayawakari.html
http://www.aozora.gr.jp/guide/aozora_bunko_faq.html

参考(比較的大がかりなもの)：

MINIXの宣言ならびに広報
http://minix1.woodhull.com/faq/mxlicense.html
https://groups.google.com/forum/#!msg/comp.os.minix/tBv9PBZiLys/MvK3BN4NKtEJ

Wikipediaのライセンスの移行・追加
http://ja.wikipedia.org/wiki/Wikipedia:%E3%83%A9%E3%82%A4%E3%82%BB%E3%83%B3%E3%82%B9%E6%9B%B4%E6%96%B0

**Comment by takahashim** [comment]
これですが、個人的には、他の方々が作ったコンテンツに対して何かをお願い・要求するよりも、新しいコンテンツを作ることを積極的にやった方がいいんじゃないかなあと思います。

@henoheno さんもB.で書かれている通り、一般論としては、ライセンスの変更を要求するのはかなりの重大事という感じで、その作者にとって大きなメリットを提示しないとまともに取り扱ってくれないことも少なくないと思います。多くの場合、ライセンスの変更でメリットがあるのは利用者であって、作者としては権利者を洗い出したり合意を取り付けたりするためそれなりに労力がかかることもある割に、明確なメリットは特になかったりするので。

（@henoheno さんの例に加えて、プログラミング言語Rubyのソースコードのライセンスは2010年9月に変更されましたが、ちゃんとした議論が始まったのは2009年8月で、ライセンス変更のためには丸1年以上の日数がかかっていました。あれはなかなか根気が要りそうでした…）

そして新しいマニュアルやガイドなどのコンテンツをCCなどのオープンなライセンスで作る上で、既存のコンテンツを利用したくなった場合には、その際に改めて使えるかどうか確認をとり、そこで必要に応じてその部分のライセンスの変更も考慮してもらう、というくらいの流れでも遅くはないのではないかなあと思いました。

**Comment by henoheno** [comment]
失念していました。

現時点の "aozorahack" GitHub Organization のplanは何でしょうか。
 "Open Source ($0/month)" である場合
「GitHub から見て Open Source であると確認できない著作物」の
取扱いは適切でないです。

企画実現のためにAを分離する意見を書きましたが
そのためにはプラン変更が必要かもしれません。

**Comment by agtc** [comment]
現在、と言うか、ここ2年くらいずーと、マニュアルの改変を続けてきていて、このアイデアソンをきっかけに加速がついて、やっと公開にこぎつけそうです。

http://www.aozora.gr.jp/aozora-manual/

ちょうど公開のタイミングなので、これにCC BY-NCあたりを付けて公開できるかどうか青空文庫の内部にお伺いをたててみます。
少々お待ちください。

**Comment by cognitom** [comment]
おおお、 @agtc さん、すばらしいです!
ちょうど「仕様書」を起こそうとしていたので、新マニュアルわかりやすくて、本当ありがたいです。

**Comment by takahashim** [comment]
@agtc さん: なんと、そういう話になっていたんですね。知らなくて変な答えをしてしまってすみませんでした…。

@henoheno さん:  現在aozorahackで使っているplanは「Free ($0/month)」です。
GitHubに載せられるコンテンツのライセンスについては、GitHub Terms of Service https://help.github.com/articles/github-terms-of-service/ によると、「第三者が閲覧すること」と「第三者がforkすること」を許可しないとダメ、と言ってるだけ(GitHub ToSのF-1)で、狭義の(OSIのオープンソースの定義に準拠した)OSSというよりは、もう少しゆるめの制約になっているという認識です。

**Comment by henoheno** [comment]
@takahashim さん

すみません、私のGitHubの理解と質問の文が良くなくて、
ミスリードを招いてしまったようです。

現時点の "aozorahack" GitHub Organization を作成された時に
"Open Source ($0/month)" を選択されませんでしたか。
そうであれば、
「GitHub から見て Open Source であると確認できない著作物」の
取扱いは適切でないと思います。

＃GitHub Help: Creating a new organization from scratch
＃https://help.github.com/articles/creating-a-new-organization-from-scratch/
＃こちらのURLの6番目の図に "Open Source $0/month" とある部分です。
＃少なくとも去年からずっとこうです。

GitHub Terms of Service
https://help.github.com/articles/github-terms-of-service/

こちらの F-1は Copyright and Content Ownership の1番目であって、該当の下りには
(あなたが)publicに設定したのであれば誰からも viewやfolkできると
youがagreeしたのと同義ですよ、と書かれています。

---

参考文献：

The GitHub Blog: Introducing Organizations (June 30, 2010)
https://github.com/blog/674-introducing-organizations

> And just like the rest of GitHub, Organizations are free for open source.
> (snip)
> Just like personal accounts, organizations are completely free for open source.
> (snip)
> Organizations can choose from the Free, Bronze, Silver, Gold, and Platinum plans. Organizations have no team limits, member limits, or collaborators - the only thing that matters is the number of private repositories. Public repositories, as always, are free.

GitHub Help: What plan should I choose? 
https://help.github.com/articles/what-plan-should-i-choose/

> GitHub provides two types of plans: free plans and paid plans.
> Both plans have the exact same features. They can have any number
>  of public repositories, with unlimited collaborators.

GitHub Help: How does upgrading or downgrading affect the billing process?
https://help.github.com/articles/how-does-upgrading-or-downgrading-affect-the-billing-process/

> If you're downgrading to a smaller (or free), the private repositories you have are instantly locked.

「有料プランをfreeにダウングレードしたもの」と、
「Open Source だからfreeであるもの」の区別がつかないのは
GitHub側のデザインの話題かもしれません。

The GitHub Blog: Choosing an Open Source License (July 16, 2013)
https://github.com/blog/1530-choosing-an-open-source-license

The GitHub Blog: Open source license usage on GitHub.com (March 10, 2015)
https://github.com/blog/1964-open-source-license-usage-on-github-com

**Comment by takahashim** [comment]
@henoheno おおお、なるほど！　そういうことだったのですね。確かにそれは微妙ですね…。
私の方ではPlans and pricing https://github.com/pricing のところの「Organization plans」のところで答えていたのでした。なんか違う話で返してしまったようですみません。

念のため、GitHubのサポートに聞いてみますね。

**Comment by takahashim** [comment]
さっそくGitHubからお返事をいただきました（さすがの早さ）。

> I'm not a lawyer, so I can't say definitively, but in general, the only thing you to be sure of is that your license allows others on GitHub.com to fork the repository. Creating a public repository requires you to allow others to view and fork the repository and its contents. As long as your license doesn't explicitly prohibit those actions, it's very likely compatible with a public repository on GitHub.com

ということで、やはり「閲覧」と「fork」を許すライセンスであればOK（逆に言うと両方を許さないものはNG）、とのことです。

**Comment by geohasegawa** [comment]
最初に書き込んでから結構な期間がたっておりますが、工作員マニュアルにCCライセンスが付与されていました！
→http://www.aozora.gr.jp/aozora-manual/

**Comment by takahashim** [comment]
@tagtagger すみません、こちら反応が遅くなりました。
そして @agtc さん、CC BY-NCの明記ありがとうございます！

で、早速なんですが、HTMLのソースを見てみたところちょっとおかしいところがあるようでした。なので、aozorahackにレポジトリを作ってそちらで作業させていただきたいです。

**Comment by takahashim** [comment]
https://github.com/aozorahack/aozora-manual に作りました。
ちょっと扱いの問題があって、改行コードをCRからLFに変更しています。

**Comment by agtc** [comment]
お忙しいところすみません。
どうぞよろしくお願いいたします。

**Comment by takahashim** [comment]
@agtc まずindex.htmlについて修正を試してみました。

現状、http://www.aozora.gr.jp/aozora-manual/index.html をHTML5 Validator https://html5.validator.nu/ にかけるとエラーが出ます。
- 検証結果: https://html5.validator.nu/?doc=http%3A%2F%2Fwww.aozora.gr.jp%2Faozora-manual%2Findex.html

これについては、 https://github.com/aozorahack/aozora-manual/pull/2 と https://github.com/aozorahack/aozora-manual/pull/3 を取り込めば解消されるようです。

この修正で問題がなさそうであれば、index-input.html と index-proofreading.html の方も対応してみます。

**Comment by agtc** [comment]
いろいろとすみません。
おそらくその修正で問題ありません。
その他もよろしくお願いいたします。

**Comment by takahashim** [comment]
@agtc ご確認ありがとうございます！　index.htmlについては取り込みました。

残りの2ファイルについては https://github.com/aozorahack/aozora-manual/pull/4 で修正してみました。修正内容は https://github.com/aozorahack/aozora-manual/pull/4/files で確認いただけます。

**Comment by agtc** [comment]
確認いたしました。ケアレスミスばかりですみません。
次回からはHTML5 Validatorを使ってみたいと思います。
いろいろとありがとうございました。

**Comment by cognitom** [comment]
よかったら、GitHub上で自動テストするように設定しましょうか?

**Comment by takahashim** [comment]
@agtc 確認ありがとうございます！　あとで取り込んでおきます。
あっと、そういえばindex-input.htmlの方は、大きすぎたせいか（？）、https://html5.validator.nu/ では検証できませんでした。そのため https://validator.w3.org/#validate_by_upload を使って検証しました。

@cognitom あっちにも書きましたが、設定していただけると良いかと思います！

**Comment by takahashim** [comment]
@agtc こちらマージしました。修正したソースはgitで取得していただいても構いませんし、面倒な場合は
- https://raw.githubusercontent.com/aozorahack/aozora-manual/master/index.html
- https://raw.githubusercontent.com/aozorahack/aozora-manual/master/index-input.html
- https://raw.githubusercontent.com/aozorahack/aozora-manual/master/index-proofreading.html

で生のファイルが見えるので、これを保存してお使いください。

**Comment by takahashim** [comment]
というわけで、一通りアップして修正もしてみたので、こちらのissueの方はいったん閉じます。
マニュアルの方に何か問題・要望等があれば  https://github.com/aozorahack/aozora-manual/issues の方をお使いいただければ。

**Comment by agtc** [comment]
みなさん、いろいろありがとうございました。
こんなふうに、オープンにしながら修正して行く方法を、htmlファイルと言いながら、流れを見させていただきました。
青空文庫の作品ファイルもこんな感じで、入力、校正が出来たらいいなあ、と思うこと頻りです。

**Comment by takahashim** [comment]
@agtc おお、そうな風に思えてもらえたのだったらよかったです！

青空文庫の作品ファイルに応用するのはそれなりに準備が必要そうですが、例えば公開後のファイルに対する修正管理などに導入するといったことは可能かもしれませんね。
