### ISSUE TITLE
リポジトリ作成希望: 「青空文庫の仕様書」

### ISSUE THREAD

**Issue by cognitom** [aozorahack/aozorahack#16]
仮で[仕様書っぽいもの](https://github.com/cognitom/aozorahack/blob/specs/specs/format.md)を作ったのですが(#15)、リポジトリとして独立させた方が扱いやすいかもということで改めて。
- name: specs
- description: 青空文庫の仕様書

**Comment by kskktk** [comment]
:+1:

**Comment by kskktk** [comment]
作成しましたー

**Comment by cognitom** [comment]
早速、ありがとうごさいまっす!

**Comment by cognitom** [comment]
あ、すみません、空のREADME.mdを入れてもらえると助かります。そしたらフォークできるようになると思うので ><

**Comment by takahashim** [comment]
@cognitom さんにspecs teamのinvitation送りました。OKしてもらえればspecsレポジトリの書き込み権限もらえるはずです

**Comment by takahashim** [comment]
あー、じゃあ私の方でREADME.md突っ込んどきます

**Comment by kskktk** [comment]
ごめんなさい。interrupt入って忘れてました。ありがとうございます！

**Comment by takahashim** [comment]
README.md追加しました :v:

**Comment by cognitom** [comment]
助かります! invitationがまだ届かなかったので、PRで送りました ;)
と書いているうちにマージされました。ありがとうございます。

**Comment by takahashim** [comment]
@cognitom invitation、メールは飛んでるはずですが、spamか何かになってないでしょうか？
（aozorahack/kosakuin のときも @cognitom さんにinvitation送ってそのままpendingになっているので…）

**Comment by cognitom** [comment]
ありゃ。失礼いたしました。メールを検索しなおしたら出てきました。Invitationは、GitHubのNotificationに出てこないのを失念してました。メンバー追加ありがとうございます m(_ _)m
