### ISSUE TITLE
「aozoraflow」リポジトリ作成依頼

### ISSUE THREAD

**Issue by ksato9700** [aozorahack/aozorahack#17]
青空文庫のテキストをGitリポジトリで管理する為の運用規約とそれをサポートするためのツールの開発のためのリポジトリが欲しいと考えています。

name: aozoraflow
description: Operation rules and tools to manage Aozora-bunko text files in a Git repository

作成をお願いできますでしょうか？
よろしくお願い致します。

**Comment by cognitom** [comment]
:+1:

**Comment by takahashim** [comment]
:ok_woman: 
README.mdも追加しておきますね

**Comment by ksato9700** [comment]
できるまでの間、手元で少し準備しようかなと思っていたらあっという間にできていました...
早速の作成、ありがとうございます！
