### ISSUE TITLE
aozorahack用のアイコン

### ISSUE THREAD

**Issue by gennei** [aozorahack/aozorahack#19]
aozorahack のアイコンが欲しいです！
slackのものと同一で問題ないでしょうか？

**Comment by kskktk** [comment]
slackで使ってるアイコンの青空写真はパブリックドメインのものなのでご自由にどうぞ！ATNDのトップと同じです。

2015年6月7日日曜日、genneinotifications@github.comさんは書きました:

> aozorahack のアイコンが欲しいです！
> slackのものと同一で問題ないでしょうか？
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aozorahack/aozorahack/issues/19.

## 

iPhoneより送信

**Comment by gennei** [comment]
:ok_hand:
