### ISSUE TITLE
リポジトリを作るプロトコルを決める

### ISSUE THREAD

**Issue by takahashim** [aozorahack/aozorahack#2]
aozorahack内にリポジトリを作りたい！とか、自分のレポジトリをaozorahack下に置きたい！という人のための流れを決める。
- [x] 案を作る
- [x] 決める
- [x] 分かりやすいところに書く
## リポジトリの作り方（案）
- Issueを作る
  - リポジトリ名(日本語)
  - リポジトリのパス名(URLに使うやつ)
  - リポジトリの紹介文
  - （所有者はIssueを作った人にすればよい？）
- 1つ以上の:+1:があれば作る
  - さすがに賛同者が誰もいなければ作らなくても良いのでは…
  - :-1: がついても気にしないことにする
    - リポジトリを作ること自体は問題ないのでは
    - 類似のリポジトリが複数できても気にしないことにすれば良さそう
    - 作る／作らないを誰かが判断するのが面倒くさい

**Comment by key-amb** [comment]
:+1: このぐらいのゆるいプロトコルがいいんじゃないかと思います。

**Comment by cognitom** [comment]
Collaboratorに対する手順としては良いように思います。
一方、外部の開発者が個人のリポジトリを立てて、上手くいきそうだったら、aozorahackに移管するというルートも欲しいですね。その場合、1つ以上の :+1: で移管を受け入れるイメージです。

外部協力者のモチベーションとして、
- なんか思いつく
- とりあえず(仮)実装する
- 他のひとの意見が聞きたい
- 公式化(?)してくれたら嬉しいな

みたいな順序になるのかと。

**Comment by takahashim** [comment]
@cognitom Collaboratorになってるかどうかに関係なく、この手順で移管したり新規で作ったりして良いかなあ、と思っています。
aozorahackも別に「公式」ではないわけですし、内部とか外部とか気にしないようにしていきたいところなのです。

**Comment by cognitom** [comment]
なるほど、たしかに。だとすると、作り始める前に「ドメイン名」とっとくかーくらいのノリですね。

**Comment by takahashim** [comment]
@cognitom そんな感じのノリですね。とはいえリポジトリを変更できるメンバーを増やしたりするのは自分のリポジトリでやってもらった方が簡単なので、体制含めてまずは自分のところで揉んでもらった方がストレスが少ないかもしれません。

**Comment by takahashim** [comment]
特に異論もなさそう（というか運用を続けてみないと何ともいえなさそう）なので、とりあえずは上記のような形にしてみます。

**Comment by cognitom** [comment]
:+1:

**Comment by gennei** [comment]
:+1:

**Comment by kskktk** [comment]
あーここを読まずにアイデアソン資料置き場のリポジトリを作ってしまいました。申し訳ありません。

**Comment by takahashim** [comment]
遅ればせながらproject.mdを追加して、README.mdからのリンクも作っておいたので、こちらは閉じてしまいますね。

何かご意見のある方は別途issueをたてていただければ。
