### ISSUE TITLE
リポジトリ移管希望:「aozora-parser.js」

### ISSUE THREAD

**Issue by cognitom** [aozorahack/aozorahack#21]
こちらで作り始めているのですが、どこかのタイミングで、aozorahackに移管できたら嬉しいです。
https://github.com/cognitom/aozora-parser.js

**Comment by takahashim** [comment]
:+1:
名前はaozora-parser.jsのままで良いですか？

**Comment by takahashim** [comment]
cf. #20

**Comment by cognitom** [comment]
名前についてですが、
- パーサであること
- JavaScript実装であること (他言語での実装も今後作られるはず)

がわかると良いなかなと。特にこだわりはないので、代案があればほかのでも構いません。

**Comment by takahashim** [comment]
:ok_woman: ではaozora-parser.jsで作ります！

**Comment by takahashim** [comment]
@cognitom https://github.com/aozorahack/aozora-parser.js こんな感じでよいでしょうか？

**Comment by cognitom** [comment]
ありがとうございます! 
あ、フォークしていただいたんですね。

![ember library mediator](https://cloud.githubusercontent.com/assets/16032/8075291/902e6bb6-0f79-11e5-8907-3698634d7c28.png)

Transfer Ornershipしちゃってもいいかなと思いましたがどうでしょう? CloneだとIssueを引き継げ無いので... (まだ少ないのであんまし関係無いっちゃないですが)

**Comment by takahashim** [comment]
おお、そうなんですね :bow: 
Transfer Ornershipはどういう手順でやるといいんでしょうか？

**Comment by cognitom** [comment]
一旦、aozora-parser.jsのリポジトリの削除をお願いします ><
そしたら、こちらからTransferをかけますので、承認してもらう、というようなフローになるかと。
二度手間になっちゃってすみません...

**Comment by takahashim** [comment]
おー、そういう流れになるんですね。
とりあえずaozora-parser.jsの方は削除しておきました。

**Comment by cognitom** [comment]
ありがとうございます。
あれっ、Organizationに渡す場合は、Admin権限がいるのか...。
- 一旦、 @takahashim さんにTransfer
- @takahashim さんから aozorahackにTransfer

とするしかなさそうですね。ちょっとやってみます。

**Comment by cognitom** [comment]
うわっち、 @takahashim さんがすでにリポジトリネットワークにいるため転送できないと言われちゃいました...

> If the user does not already have this level of access, a temporary admin team can be created with only the user. The user sending the repository is the only one who can perform the transfer.
> https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization

なるほど...、一時的にAdminアクセスをつけてもらうことは可能でしょうか?

**Comment by takahashim** [comment]
@cognitom とりあえずこれでいけますか？

**Comment by cognitom** [comment]
ありがとうございます! うまくいったみたいです :-)
https://github.com/aozorahack/aozora-parser.js

パーミッションを戻していただければ幸いです m(_ _)m

**Comment by takahashim** [comment]
@cognitom  :100: 戻したというか、admin用のTeamを削除しておきました。
