### ISSUE TITLE
リポジトリ作成依頼「aozora.json」

### ISSUE THREAD

**Issue by key-amb** [aozorahack/aozorahack#23]
昨夜、@cognitom さん, @ksato9700 さんと話して [kosakuin](https://github.com/aozorahack/kosakuin) の初期ゴールとしては、npm のような「作品の完成品置き場」を目指すことにしました。
議論の内容のメモは [こちらの Gist](https://gist.github.com/key-amb/f39233a81c85e250d4e5) に置いています。

そこで、その完成品には npm の package.json のような、JSON 形式のメタデータを付加するようにしたいと考えています。
このリポジトリは、そのフォーマットを定めるものです。

よろしくお願いします。

**Comment by cognitom** [comment]
:+1:

**Comment by takahashim** [comment]
作ってみました。
https://github.com/aozorahack/aozora.json
@ksato9700 さんもアクセス権を登録しておきますか？

**Comment by takahashim** [comment]
ちなみにJSON形式の書誌情報としては、NDLのものがあるようです（元はRDF?）

メタデータ: http://iss.ndl.go.jp/information/metadata/
sample: http://iss.ndl.go.jp/books/R100000002-I000011125696-00.json

**Comment by ksato9700** [comment]
@takahashim さん
はい、アクセス権いただけると助かります！

**Comment by cognitom** [comment]
@takahashim さん、ありがとうございます!
Dublin coreとかのRDF方面は、語彙(フィールド)が多すぎてうむむと思っていたんですが、NDLのjsonは適当に端折ってて良い感じですね。これに準拠して、いくつかの青空文庫拡張をするのはありかも。

**Comment by takahashim** [comment]
@ksato9700 追加しておきました！

**Comment by ksato9700** [comment]
@takahashim ありがとうございます。

**Comment by key-amb** [comment]
ありがとうございました！！ クローズしますね。
