### ISSUE TITLE
リポジトリ作成依頼「hinagata」

### ISSUE THREAD

**Issue by key-amb** [aozorahack/aozorahack#24]
https://github.com/aozorahack/aozorahack/issues/23 に関連して、作品パッケージを作成する際の雛形になるリポジトリを作りたいと考えています。
名前はまだ決まってません。このイシュー内で決めたいと思います。

※追記
「hinagata」としたいと思います。

**Comment by key-amb** [comment]
名称案:
- hinagata
- kosakukit
- aozora-prototype

**Comment by key-amb** [comment]
昨日も思ったのですが、 #23 aozora.json をこっちに含んでもいいかも。まあ、でも後で考えればいいかな、とも思います。

**Comment by cognitom** [comment]
昨日はおつかれさまでした!
リポジトリ作成について :+1:
名前はどれがいいですかね。

**Comment by ksato9700** [comment]
"hinagata" に :+1:

**Comment by key-amb** [comment]
"hinagata" で行こうかと思います！
わかりやすいし、既存ソフトウェアの名前ではあまりなさそう。

**Comment by takahashim** [comment]
名前とレポジトリ名はhinagataで了解です。
で、何（何の雛形）についてのレポジトリになるのかちょっとよく分からなかったんですが、レポジトリの説明としてはどんな感じになりますか？

**Comment by key-amb** [comment]
おっと。そうですね。

「工作院(kosakuin)にアップロードされる作品パッケージの雛形になるもの」というところでしょうか。

**Comment by takahashim** [comment]
@key-amb ありがとうございます、ではそれで作成します！

**Comment by takahashim** [comment]
作りました :hatched_chick:
https://github.com/aozorahack/hinagata
