### ISSUE TITLE
YAPC::Asia Tokyo にトーク応募しませんか？

### ISSUE THREAD

**Issue by key-amb** [aozorahack/aozorahack#25]
ご存知の方もいるかと思いますが、8/20-22 に東京ビッグサイトで最後の YAPC::Asia Tokyo が行われます。
http://yapcasia.org/2015/

もともと Perl のイベントですが、Perl 以外のトークもたくさん応募されています。
それにトーク応募しませんかという提案になります。
〆切は **6/15(月)** です！
(もっと早く言わなくてゴメンナサイ。。)

テーマや内容としては次のようなところを想定しています:
- aozorahack の紹介
  - 誕生の背景
  - 第1回アイディアソン
- 青空文庫の状況、システム構成
  - 歴史
- 現在進行中のプロジェクト
  - kosakuin, aozora-parser.js, ...
- 青空文庫と aozorahack の未来予想図

発表者は「自分でやれ！」と思われる方もいるかもしれませんが、 @kskktk さんか @takahashim さんを推薦したいなと思います。
(元祖高橋メソッド見たい！)

ご一考下さい～

**Comment by takahashim** [comment]
YAPC::Asia 2015はチケットは買ったので参加予定ではありますが、私の方からは8月の時点では30分や60分のトークに出せるほどまでのネタがないかな…と思っています :worried:
（一年くらい順調に進めば何かしらの成果が出てくることも期待したいところではありますが）

どちらかというとトーク枠よりもLT枠であれば応募してみてもいいかもとは思います。LTであれば、「こういうことを進めているので興味のある人は参加してください」という告知だけでも十分メッセージになるので（今回のYAPC::AsiaでLTがあるのかどうかは分からないのですが）。

**Comment by key-amb** [comment]
なるほど。確かにLTもよさそうですね〜
まだ募集は掛かってませんが、きっとあるのではないかと。

**Comment by key-amb** [comment]
募集終わったのでクローズしますー
