### ISSUE TITLE
リポジトリ作成依頼「bungakubu」

### ISSUE THREAD

**Issue by nanbuwks** [aozorahack/aozorahack#29]
定期イベントやハッカソンなどで作業を行う上でのレポジトリです。
まず第一回目の「青空シャッカソン #1 〜青空文庫の入力ハッカソン〜」
https://atnd.org/events/67975
では、底本の原データ登録場所、入力登録場所、校正作業場所にしようと思います。
よろしくお願いします。

**Comment by takahashim** [comment]
:+1:
ではbungakubuで作っておきますね。

**Comment by takahashim** [comment]
https://github.com/aozorahack/bungakubu で作りました。

**Comment by nanbuwks** [comment]
ありがとうございます。issue closeします。
