### ISSUE TITLE
txt2xhtmlのリポジトリを作りたいです

### ISSUE THREAD

**Issue by takahashim** [aozorahack/aozorahack#3]
「青空文庫 組版案内」で配布されているtxt2xhtmlをhackしやすいようにしたいのでした。
- 青空文庫 組版案内 http://kumihan.aozora.gr.jp/
- txt2xhtmlダウンロード http://kumihan.aozora.gr.jp/slabid-14.htm 
## txt2xhtml について
- 作者: 青空文庫
- ライセンス: CC0 1.0
- 動作環境: Ruby 1.9
- 説明: http://kumihan.aozora.gr.jp/slabid-9.htm
- 最新版: version 0.3.1 - 2012年3月1日

**Comment by cognitom** [comment]
:+1: 欲しいですね。
スタート地点はここかな、という気がしてました。

**Comment by key-amb** [comment]
:+1: 

こういうのがあったんですね。
ここで配布されているものと同じものを再実装する感じですかね。

**Comment by takahashim** [comment]
@key-amb このスクリプトについては再実装というよりは、そのままこれを元に改修してもいいかなあ、と思っています。ライセンスもCC 0なので。

ただ、素朴に改修しようとすると、
- 全クラスが１ファイルに収まっているので分割してテストしやすいようにしたい
- クラスの命名ルールが特殊なので普通のRubyのルールにしたい（Embed_Gaiji_tag -> EmbedGaijiTag）
- スクリプト自体の文字コードがShift_JISじゃなくてUTF-8にしたい（ただしShift_JIS or CP932の青空文庫テキストファイルを扱えることはMUST）

みたいところに手を入れることになって、そうするとコードレベルの互換性が崩れるので、別名にした方がいいのかな…という気になってくるのでした。

**Comment by takahashim** [comment]
あ、でもRubyじゃなくて他の言語にportingしたいというのがあればそれも歓迎です！
（JS版とか欲しい…）

**Comment by key-amb** [comment]
なるほどー 補足ありがとうございます！

よりよいものを作るのであれば、改修して置き換えることを目指すでよさそうですね。
ソース見てなくて恐縮なのですが、きっと大工事する感じですかねー。

**Comment by cognitom** [comment]
JS版あるとオンラインプレビューできるようになりますね。というか、[atom](https://atom.io)のプラグイン化できる説。
Ruby版については、[aozora4reader](https://github.com/takahashim/aozora4reader)からの方がむしろ近道ですか?

**Comment by takahashim** [comment]
@key-amb コード自体は整理されているので、大掛かりな工事にはならないはずです。が、手を入れだすとキリがなくなるかも…。

@cognitom atomプラギン欲しいですよねえ。
（aozora4readerの構文解析部分はカオスなので早く捨てたいのでした…）

ちなみにJavaについては https://github.com/hmdev/AozoraEpub3/ のエンジンがあります。GPLv3。注記の対応は不十分なところがあるかもしれません。

**Comment by henoheno** [comment]
配布パッケージ中に情報が埋め込まれていますから
どこかに既にリポジトリが存在する可能性があります。

 $ cat release.info
 changeset:   75:cefd2d6ca1bd
 date:        Thu Mar 01 00:00:39 2012 +0900
 summary:     Added tag 0.3.1 for changeset c1de620ca314

規模の大小はあれど、リリースエンジニアリングのための
パッケージ生成スクリプト等をお作りになられているだろうとも
想像します。

リポジトリを(再)生成する場合ですが、txt2xhtml-latest.tar.gzの
古いアーカイブがどこかにあると良いですね。

 version 0.1.0 - 2010年4月1日
 version 0.2.0 - 2010年6月28日
 version 0.3.1 - 2012年3月1日

**Comment by takahashim** [comment]
「Mercurialの気配」！　というご指摘をいただいたので探してみたところ、
Google Codeにそれらしきものがありました！
https://code.google.com/p/aozora-collection/source/browse/

**Comment by takahashim** [comment]
Google Codeの方、0.3.1リリースで止まっているのと、特にリリース用スクリプト的なものは含まれていないようですね…。
あと、aozora-collectionリポジトリはGPLv3.0になっているのが気になりました。

**Comment by cognitom** [comment]
とりあえず、Google Codeからエクスポートしちゃいませんか? まだ、誰もGitHubに持ってきてはいないようです。
https://code.google.com/export-to-github/export?project=aozora-collection

あと、念のためnpmで検索したところ、1件出てきました。

> 青空文庫工作員作業マニュアル 2.入力-1にある仕様のうち、ルビと［改ページ］タグのみをサポート
> https://www.npmjs.com/package/aozora-ruby-parser

**Comment by henoheno** [comment]
見つかったならば結果オーライなのです。

> Google Codeの方、0.3.1リリースで止まっている

最新のパッケージと対応しています。hash(cefd2d6ca1bd)も同一ですね。

> version 0.3.1 - 2012年3月1日

ただ、「txt2xhtmlツール全部入り」txt2xhtml-latest.tar.gzと比較すると
最終配布物そのものではなく、その一部であることは明らかです。

著者について。
aozora-collection のオーナーは bluesky.... at gmail.com とありますね。
配布物(著作物)には著者が明記されていない問題がありました。
著者が特定できて存命で合意が得られれば、その方が著述した部分は
その方によって再ライセンス可能ですが
その辺りどうなのでしょう。やはり駄目なのでしょうか？

配布物のライセンスについて。
配布物に明示されています。

 $ cat README
 (snip)

> 配布条件
> 
> txt2xhtmlツール
> CC0 1.0(http://creativecommons.org/publicdomain/zero/1.0/)によります。
> 
> 外字グリフデータ
> JIS X 0213 の画像ファイルは、jiskan16-2000(http://www12.ocn.ne.jp/%7Eimamura/jisx0213.html)を元にしたHabian(http://wakaba-web.hp.infoseek.co.jp/FONT/Habian/Habian.htm)をdoodle(http://www.vector.co.jp/soft/winnt/prog/se219120.html)で変換して作りました。
> 
> jQueryは、配布ファイル内に記載されているライセンスによります。
>  (snip)

このように、「txt2xhtmlツール全部入り」txt2xhtml-latest.tar.gz には
複数の著作物が区別されて収められていると認められるので、
穏当に継承するのであれば、やはり著作物/ライセンス/管理単位ごとに
ディレクトリやリポジトリを構成したうえで、その外部や上位空間に
パッケージ生成スクリプトを用意するスタイルが
管理者の労力を削減する意味で堅実でしょう。
(これは開発環境やリポジトリのデザインに関する言及です)

aozora-collection のソースに jquery-1.4.2.min.js が混じっており
著作物およびライセンスを整理しきれいていない気配がする点が気になります。
READMEやLICENSEファイル等で明確に言明しているのであればまだ理解できますが
このソースについては(全部入りパッケージと異なり)そうなっていません。

> - Copyright 2010, John Resig
> - Dual licensed under the MIT or GPL Version 2 licenses.
>   *
> - Includes Sizzle.js
> - http://sizzlejs.com/
> - Copyright 2010, The Dojo Foundation
> - Released under the MIT, BSD, and GPL Licenses.

aozora-collection のProject InformationにCode Licenseとして
GPL v3 とあるのは、現時点では配布物に反映されていないように見え
実体が無いように見えます。

著作・著作物・ライセンスを尊重しない活動は生き残れません。
複数の目でもって各自現物を洗っていただき
適当な混在が起こらないようご留意いただければと思います。

**Comment by cognitom** [comment]
作者の方と連絡がつくと良いですね...、[Google Codeの変更履歴](https://code.google.com/p/aozora-collection/source/list)を見ると4,5人がコミットしているようです。

あ! 工作員マニュアルにお名前を発見。[そらもよう](http://www.aozora.gr.jp/soramoyou/soramoyou2010.html)にも。[この論文](http://2008.conf.ai-gakkai.or.jp/program/pdf/100167.pdf)の著者の方っぽいので、どなたか連絡つかないかしら...

> txt2xhtmlは、藤井遼さんによって書かれました。
> 2010年３月末公開分までに利用した旧変換プログラムは、大野裕さんによって書かれました。 
> http://www.aozora.gr.jp/KOSAKU/MANUAL_5.html

**Comment by henoheno** [comment]
※主語を明確に記載するため、余計に長くなっています。

> aozora-collection のProject InformationにCode Licenseとして
> GPL v3 とあるのは、現時点では配布物に反映されていないように見え
> 実体が無いように見えます。

公式の配布物と aozora-collection は ライセンスが異なる、と
見なすべきである事を認識し、もう少し整理しました。

CC0 が良いか、GPLv3が良いのかは
中身を知る方にご判断いただきたいです。
私にはこのツールにどの程度力を注ぐべきかの知識もありません。
検証ならびにご意見をお待ちしております。

---

[1] txt2xhtml-latest 等の配布物 (t2hs.rbを含む): CC0 1.0

CC0 1.0です。 

単体配布版 t2hs-latest が最も判りやすいのですが、
t2hs.rb しか実質的に配布していない状況で、説明書きとして

> 青空文庫で公開されているテキストデータ（注記を付加したもの）から
> XHTML形式のデータを生成するプログラム。
> (snip)
> 配布条件
> 
> txt2xhtmlツール
> CC0 1.0(http://creativecommons.org/publicdomain/zero/1.0/)によります。

とあり、この t2hs.rb については (ヘッダに何も書いてありませんが)
CC0 1.0ライセンスで公開する意思があったと言えます。

CC0 1.0 であることに異論がないのであれば、これを継承するにあたり
著作者への連絡は不要かと思います。
アーカイブがある程度遺されているならば、
それらからリポジトリを生成することは可能です。割愛します。

なお「全部入り」の場合は説明が

> 青空文庫で公開されているテキストデータ（注記を付加したもの）から
> XHTML形式のデータを生成するプログラムと必要なファイル群。

このように書かれており、上で触れていますが
CC0 以外のパッケージや異なる著作物を含んでおり
そのことを(漏れがあるか不明ですが)適切に明示しようとしている
ことがうかがえます。

---

[2] aozora-collection のhgリポジトリ (t2hs.rbを含む): GPL v3

これをGitHubにエクスポートすることは技術的に可能かもしれませんが
その場合 GPL v3 として扱うのが適当でしょう。なぜならば：

リポジトリブラウザで見ると、(README や LICENSE による)
ライセンスの説明がなく、不十分です。
その意味で takahashim さんの心配した通り、
Project Information の "GNU GPL v3" という記載から
「これ (t2hs.rbを含む) は GPL v3 ですよ」と言っていると
読むしかありません。

GPL v3 であることに異論がないのであれば、著作者への連絡は不要かと思います。
名前は aozora-collection ではない適切な何かにすべきかと思います。

ただし jquery-1.4.2.min.js は (CC0でもないし) GPL v3 でない事が
ヘッダから明らかですが、それをひっくるめてGPL v3であるかのように
扱うのは不当です。(README や LICENSE による)適切な明示を行うか、
さもなくば著作物の分離をすべきです。

---

[3] 同一性

上記それぞれの t2hs.rb は、 diffで比較する限り同一のファイルです。
Mercurialのhash値が同一ですし、当然といえばそうです。
その意味で、著作者は cognitom さんご提示の通りかと思います。

https://aozora-collection.googlecode.com/hg/t2hs.rb
http://kumihan.aozora.gr.jp/download/t2hs-latest.tar.gz

---

[4] まとめ

これらの状況から、このツールは CC0 1.0 で配布されていますが
残念ながらリポジトリとしては GPL v3  のようにしか見えない状況で
結果として変則的なデュアルライセンスの運用が取られているかのように
見えてしまっています。

仮にaozora-collection のhgリポジトリのライセンスが 「CC0 1.0」か
「CC0 1.0 と GPL v3 のデュアルライセンス」と明記されていたり
コミッターもそれに同意していることが確認できる記録があったならば
状況が変わるのですが。

※これまでに何度もCC0でリリースしているのかもしれないので
　それが確認され次第、気持ちは想像できますが状況証拠です

---

[5] 繰り返さないために

著作する側の心得として
永続性を持たせたいかどうかにかかわらず
配布物のトップディレクトリやファイルのヘッダなどに
明確に著作、著作の時期、ライセンスを記載する癖をつけましょう。

**Comment by takahashim** [comment]
この辺りは単に調査しただけではよく分からなかったので、青空文庫の方に確認してみますね。
個人的には、txt2xhtmlに関しては、aozora.gr.jpで配布しているのがCC0の方なのと、Google Codeの方は開発が止まっているので、aozora.gr.jpのソースをベースにした方がよいかな…と思っています。
(外字グリフデータの方は、経緯が複雑な上に最近ではJIS X 0213が使える環境も一般的になってきたので同梱しなくても良いのではないかな…と思いつつあります)

**Comment by takahashim** [comment]
<blockquote class="twitter-tweet" lang="ja"><p lang="ja" dir="ltr"><a href="https://twitter.com/takahashim">@takahashim</a> <a href="https://twitter.com/agtc">@agtc</a> 私は後者は初めて知ったのですが（念のため確認してみます）、青空文庫公式のものは、組版案内にあるものと考えてくださってよいかと思います。</p>&mdash; 大久保ゆう (@bsbakery) <a href="https://twitter.com/bsbakery/status/605404485792301056">2015, 6月 1</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

https://twitter.com/bsbakery/status/605404485792301056

とのことなので、kumihan.aozora.gr.jpにあるソースをCC0にしてレポジトリに入れるのがよいかなーと思っています。

**Comment by jn1uqb** [comment]
先日はおつかれさまでした。遅ればせながらjoinしました。

件の方は、こちらの方ですね。
http://www.slideserve.com/deon/allegrograph-web 
http://www.sakurai.comp.ae.keio.ac.jp/2007/roy/ 

もちろん野口さんはじめ青空文庫の方々はご存知だと思いますが、連絡取れるかなぁ

**Comment by takahashim** [comment]
@jn1uqb 確かお忙しい方でレスポンスに時間がかかるかも、というお話だったような…。

それはさておき、txt2xhtml内の本体のファイル、t2hs.rbについて、テストを書きながら調査しています。

#### 気になった点1: 名称を変えた方がいいかも。

現状ちょっと名前が混乱気味に見えます。
- プログラム名: txt2xhtml
- スクリプト名: t2hs.rb
- t2hs.rb内のクラス名: Aozora2Html

RubyのパッケージマネージャであるRubyGemsでパッケージ化しようとしているのですが、わかりやすさからいくとAozora2Htmlが良さそうな気もします。

#### 気になった点2: 最新のRubyだと挙動がちょっと違う

元はRuby 1.9用のスクリプトだったのですが、最新版のRuby 2.2で動かすと、出力されるファイルに違いがありました。
これはHTMLのエスケープが防御的になったせいで、そのため`'`を`&#39;`に変換するようになっています。
大きな違いではありませんが、どうしたものかなあ…というところです（HTMLの意味的には等価なので無視してもいいんじゃないかな…という気持ちが9割）。

**Comment by takahashim** [comment]
今のところこんなかんじです。 https://github.com/takahashim/aozora2html

**Comment by henoheno** [comment]
aozora2html という名称は、他の候補よりも素直に聞こえます。

---

推移を観察できるようにするため、
CC0で公開されている「全部入り」相当のパッケージ３点を
同じリポジトリにリリース順にコミットしたものを作ってみました。

https://github.com/minix-up/aozora2html-testrun01/tree/master/txt2xhtml-latest
https://github.com/minix-up/aozora2html-testrun01/commits/master/txt2xhtml-latest/t2hs.rb

現時点では、タグやコミット時刻などの装飾はなく
構築後にパッケージとの照合をしていないので、何らかのエラーや不整合もありえます。

---

元になっているパッケージはこちらにあります(ありました)
http://kumihan.aozora.gr.jp/download/

今も公開されているなかで最古の全部入りパッケージ txt2xhtml-590cd17e60bc.tar.gz は、ユーザーおよびグループが www-data/www-data なので、当時のwebサーバー上で作成されたものと推測されます。
(それ以降は root/root で作成されています)

一部、誰にも書き込み権限が無いディレクトリやファイルが含まれています。
css/kentenbosen は Mac で作業が行われた形跡がありました。

残りのパッケージやその中身は調べていません。

---

2015/06/21版

https://github.com/minix-up/aozora2html-testrun02
https://github.com/minix-up/aozora2html-testrun02/commits/master/t2hs.rb
- ユーザー名をaozorabunkoに
- リポジトリのパスを簡潔に

**Comment by henoheno** [comment]
@cognitom さんが見つけられた、aozora-collection リポジトリにおける複数の著作者(アカウント)ですが、ごく一部を除き同一人物である可能性があります。

[aozora-collection]$ hg history | grep ^user: | uniq | sort | uniq | tr '@<>' '_()'
user:        aozora
user:        bluesky
user:        bluesky.collection.code
user:        Kevin Fujii(kevin_neophilia.co.jp)
user:        roy_anette
user:        roy_brodee
user:        roy_downspout
user:        roy_vitz

royという語は藤井さんの慶応時代のメールアドレスにおいて
ユーザー名として使われているキーワードです。
http://www.sakurai.comp.ae.keio.ac.jp/2007/roy/ ←ディレクトリ名にも

また、コミットログを読んでみると
roy@vitz はリポジトリに 0.1.0 と 0.2.0 のタグを打っており
roy@anette はリポジトリに 0.3.0 と 0.3.1  のタグを打っていますが
バージョン番号のタグを打つというのは、リリースに影響する作業であり
仮にそれぞれが別人であるとすると、作業の移り変わりが不自然です。
(以下に挙げる一覧も参照ください)

これらの状況から、roy@\* は藤井さん当人であって、所在や場面に応じ
アカウント(作業場所)を使い分けられていたのではないかと推測します。

ソートしない登場順は以下の通りですが (上の項目ほど新しい)：

[aozora-collection]$ hg history | grep ^user:| uniq -c | tr '@<>' '_()'
      9 user:        roy_anette
     11 user:        roy_vitz
      1 user:        roy_anette
      1 user:        roy_vitz
      2 user:        roy_anette
      9 user:        roy_vitz
      1 user:        Kevin Fujii(kevin_neophilia.co.jp)
      7 user:        roy_vitz
      2 user:        roy_downspout
     20 user:        roy_vitz
      1 user:        roy_brodee
      2 user:        roy_vitz
      1 user:        bluesky
      1 user:        roy_vitz
      2 user:        aozora
      1 user:        bluesky.collection.code
      2 user:        roy_vitz
      1 user:        aozora
      1 user:        bluesky.collection.code
      1 user:        roy_vitz

aozora、bluesky、bluesky.collection.code のユーザー名は初期にのみ登場しますから
藤井さんご本人の可能性が高いように考えられます。
そうでないとこれまでの情報と矛盾が生じます。

http://www.aozora.gr.jp/KOSAKU/MANUAL_5.html

> txt2xhtmlは、藤井遼さんによって書かれました。

唯一のメールアドレスのドメイン neophilia.co.jp は
青空文庫ゆかりのドメインのようですから、追跡可能と思われます。

なお、aozora-collectionのOwnerのメールアドレス(をなぜかうまく取り出せないのですが)
も bluesky で始まっています。個人的には協力者ではなくご本人であるように推測します。

---

補足： 構築時期について

[aozora-collection]$ hg history | grep ^date: | cut -b 34-38 | sort -nr | uniq -c
     11 2012
     34 2010
     31 2009

**Comment by jn1uqb** [comment]
そうですね。

コミットログやそのアカウントを見ても、3〜4人だと思います。
基本的には、遼さんお一人で書かれたと考えて差し支えないでしょう。
https://twitter.com/aobeka/status/11397842768

**Comment by takahashim** [comment]
こちらずっと反応できなくてすみません。
@kskktk さんに聞いたところ、藤井さんとはしばらく連絡がとれてないそうなので、プログラム自体はCC0で公開されていることもありますし、まずは配布条件でCC0になっている部分だけ(txt2xhtmlツールと「注記一覧」記入例）取り込みたいと思います。

http://kumihan.aozora.gr.jp/slabid-15.htm

**Comment by cognitom** [comment]
:+1:

**Comment by takahashim** [comment]
RubyGemsとしても登録しました。

https://rubygems.org/gems/aozora2html

`gem install aozora2html` でインストールできるようになりました（ついに）。

**Comment by takahashim** [comment]
というわけで、こちらのissueの方は閉じておきます。何か変更したい点等あれば、 https://github.com/aozorahack/aozora2html の方にいただけるとありがたいです。
