### ISSUE TITLE
OSC 2015 Tokyo/Fall への出展

### ISSUE THREAD

**Issue by nanbuwks** [aozorahack/aozorahack#30]
OSC 2015 Tokyo/Fall が以下のように開催されます。

日程：2015年10月24日(土) 10:00～18:00（展示：11:00～17:30）
　　　　　　 10月25日(日) 10:00～17:30（展示：10:00～16:00）
会場：明星大学 日野キャンパス 28号館 2F(OSC受付)

http://www.ospn.jp/osc2015-fall/

出展受付は8/24締切です。
このissueで、検討していきましょう。

**Comment by takahashim** [comment]
すみません、出遅れてたら締め切りが明日でした…。

出展するとして、何をどう出すといいんですかね？

**Comment by nanbuwks** [comment]
今回は、
・ブース出展　ハッカソンやってますという案内のチラシ、青空文庫のチラシを作って置いておくのでいいかと。
・セミナー　「青空文学部に参加しませんか　という呼びかけ」というような内容で良ければとりあえず僕が登壇することにして申し込みしてしまおうかと思います。

僕は別に主宰している団体のブースで申し込みをするので、ブースの申込者の名前は別の方のお名前を使わせていただけないかと。
ブース場所ですが、僕のブースと隣接希望を出しておけば、ブース番は僕がかけもちできますので、当日は僕ともう一人ぐらいで回せると思います。

**Comment by takahashim** [comment]
名前の方は私の名前で出すので問題ないです。土曜日ならブース番もできそうです。
ブースとセミナーの内容もそんな感じでいいですかね。

**Comment by takahashim** [comment]
OSC(オープンソースカンファレンス)なのでOSSプロダクトがばばーんとあるような形じゃないのが気になっているのですが（あるいはそれまでに何とかする？）、むしろ「オープンデータとしての青空文庫」を中心にしてOSS的な活動をやっていきたい、という見せ方ができるといいんでしょうか。

**Comment by kskktk** [comment]
香月です。反応遅れて申し訳ありません。
（そしてもろもろ遅々としておりそちらも申し訳ありません！）

OSCに出展、僕も賛成です。
10/24と25の僕のスケジュールも空けました。
@nanbuwks さん、貴重な機会のご提案本当にありがとうございます！

そして高橋さんの

> むしろ「オープンデータとしての青空文庫」を中心にしてOSS的な活動をやっていきたい、という見せ方ができるといいんでしょうか

に賛成です。

「あれだけ騒いだけど、けっきょくどうなったの？」というのを知りたいひとも多いので
OSCでaozorahackでOSSプロジェクトをはじめますよーということ
具体的な動きとして青空文学部があることとその活動報告、
そして次回ハッカソンの発表ができればいいと思っています。
（要はある種の記者レク的なものにセミナーができれば本の未来基金的にも嬉しい）

あとこれは（僕が責任を取るという意味で）香月名義で申し込ませてください。
青空文庫の大久保さんの内諾もいただいております。

**Comment by takahashim** [comment]
おお、そうなんですね。では香月さんの方から申し込みをお願いしてしまうのでよいんでしょうか＞  @nanbuwks , @kskktk 

OSC 2015 Tokyo/Fallの申し込みファイルは（なぜか私も持っていたので）香月さんにメールしておきますが、その前にまずお問い合わせフォームの方から一度コンタクトとった方が良さそうです。

ブースの場所は@nanbuwks さんのところと隣接でお願いした方が良いかもですが、ジャンルで分けられそうな気もするので、その辺は明後日以降でも事務局と相談してみるのが良いかもです。

**Comment by nanbuwks** [comment]
では、それでお願いします。
セミナーは他に人がいなければとりあえず僕がしゃべるつもりでしたが、他の方の都合がつけばそちら優先で。あるいは何人かで発表を分担にしてもいいですね。

**Comment by cognitom** [comment]
日曜日のブース番入ります! (その後動けてなくてスンマセン >< )

**Comment by kskktk** [comment]
今申し込みしましたー

**Comment by cognitom** [comment]
:+1:

**Comment by nanbuwks** [comment]
出展団体の名義は何になったでしょうか。
僕は「秘密結社オープンフォース」でブース出展申し込みしますが、隣接希望出しておきましょうか？

**Comment by kskktk** [comment]
ギリギリで申込書提出しました。aozorahackで申し込みをしています。
こちらで「秘密結社オープンフォース」との隣接希望を出しておきました！

**Comment by kskktk** [comment]
■セミナータイトル
aozorahackの今までとこれから
〜インターネット電子図書館「青空文庫」をエンジニアリングで支える〜

■内容
5月30日に開催された「Code for 青空文庫」アイデアソン。青空文庫を技術的に支えるために多くのエンジニアたちが立ち上がり、エンジニアコミュニティが作られました。本セミナーでは現状の青空文庫を支えているインフラについて解説し、その未来像の青写真を示します。またアイデアソンで生まれた青空文学部などの活動も紹介します。

**Comment by kskktk** [comment]
申し込み受理されましたー
http://www.ospn.jp/osc2015-fall/

**Comment by takahashim** [comment]
@kskktk おお！　おつかれさまでした！

**Comment by takahashim** [comment]
タイムテーブル出てました
https://www.ospn.jp/osc2015-fall/modules/eventrsv/?id=2

aozorahackのコマは13時からです
https://www.ospn.jp/osc2015-fall/modules/eguide/event.php?eid=64

**Comment by nanbuwks** [comment]
出展内容、およびセミナーの段取りしていかないといけないですね。
出展はパンフ作って配布というのでいいと思います。
セミナーは、誰が喋ることで進めましょうか。

**Comment by nanbuwks** [comment]
パンフの印刷は、印字品質悪くてよければ僕がインクジェットプリンタで印刷する方法で１円／枚程度でカラー印刷できます。あらかじめpdfなどで原稿をいただければ。
青空文学部の案内パンフは僕が作りましょうか。あとは？

**Comment by kskktk** [comment]
お返事遅くなりまして申し訳ありません（通知メールが全部SPAMに……）。
TPP関連でバタバタしていましたが
ようやく一段落は付きそうなので今後はガッツリやっていきます。

OSCに関するコストは本の未来基金で出す決済はとれましたのでこちらでやりますよ。
セミナーは取り急ぎ香月と @nanbuwks さんは決定という感じでいいでしょうか？
ぜひ @takahashim さんにもお願いしたいところですが…いかがでしょうか？
一度オンラインででもお打ち合わせしたいですね。

@nanbuwks さん
PCのMACアドレスを教えてください。申請をしておきます。

**Comment by takahashim** [comment]
@kskktk ええと、いろいろあって日曜日にaozorahackの次のコマのパネルディスカッションに出ることになったので、aozorahackのセミナー枠の方にも参加できる予定です。

**Comment by nanbuwks** [comment]
セミナーと、展示の内容を決めていきましょう。以下埋めていきませんか。

セミナー：10/25：2日目13:00-13:45 aozorahackの今までとこれから ～インターネット電子図書館「青空文庫」をエンジニアリングで支える～
担当：aozorahack 
講師：香月 啓佑・他各担当者 
@kskktk ・・・本の未来基金と青空文庫、そして今後のイベントの説明
@takahashim ・・・ 青空文庫とOSS
@nanbuwks  ・・・青空文学部の紹介について

展示：aozorahack [Web アプリ/公共・自治体/オープンデータ]    インターネット電子図書館「青空文庫」を支えるために集まったエンジニアのコミュニティ。青空文庫をエンジニアリング面で支えるために行っている活動の紹介など
@kskktk ・・・土曜日入りますー
@takahashim ・・・
@cognitom ・・・日曜日のブース番入ります!
@nanbuwks  ・・・青空文学部で行ったシャッカソンについてパンフを作る／土日ブース掛け持ちで入ります。

**Comment by nanbuwks** [comment]
ブースレイアウト見たら、僕の「秘密結社オープンフォース」と２コイチで、机半分のスペースになってますね。これでもOKですか？　「秘密結社オープンフォース」の展示はいっぱいあるので、干渉しそうです。レイアウトの修正は10/5までとなってますが、必要なら今からでも机1つ確保のリクエストを出せるかと思います。

**Comment by kskktk** [comment]
@nanbuwks さん、修正依頼お願いできますか？

---

香月 啓佑 / Keisuke KATSUKI
Follow @kskktk on Twitter.

2015年10月8日 12:23 nanbuwks notifications@github.com:

**Comment by nanbuwks** [comment]
「秘密結社オープンフォース」は机半分でもOKなので、「aozorahack」の机１つ確保のリクエストの方がいいかと思います。僕からaozorahack枠を机1つにと出しておきましょうか？

**Comment by kskktk** [comment]
@nanbuwksさん
お願いできると嬉しいです。もし当事者じゃないとだめだと言われたら動きます。おまかせしっぱなしで申し訳ありません。

---

香月 啓佑 / Keisuke KATSUKI
Follow @kskktk on Twitter.

2015年10月8日 13:49 nanbuwks notifications@github.com:

**Comment by kskktk** [comment]
@takahashim 登壇ありがとうございます！また別途ご相談させてください。

**Comment by nanbuwks** [comment]
OSC事務局にリクエスト出しています。修正締め切り過ぎてますので机1つ確保の可否は少しお待ちくださいとのことです。

**Comment by nanbuwks** [comment]
11月にaozorahackやります！ということでOSCでアナウンスしたいですね。いかがでしょう？

**Comment by nanbuwks** [comment]
ブースレイアウト、OSC事務局側で調整していただきました。aozorahackで机１つ確保できています。

**Comment by takahashim** [comment]
@nanbuwks 調整ありがとうございました。

> 11月にaozorahackやります！ということでOSCでアナウンスしたいですね。いかがでしょう？

おお！　よいと思います :+1:

**Comment by kskktk** [comment]
@nanbuwks さんもろもろ調整ありがとうございます！
そろそろ配布物など作りたいと思っています。
合わせて本の未来基金からも声明を出す予定です。

一度アジェンダ設定をしてオンラインで打ち合わせを持ちましょう。

**Comment by kskktk** [comment]
チラシ表紙です。
![aozorahack](https://cloud.githubusercontent.com/assets/2081248/10577259/90e00154-76a4-11e5-8b78-0763ec694a93.jpg)

**Comment by kskktk** [comment]
チラシ裏面です
![aozorahack_ura](https://cloud.githubusercontent.com/assets/2081248/10578339/79ba4234-76ac-11e5-866d-c7179e6d4814.jpg)

**Comment by cognitom** [comment]
:+1: :+1: :+1:

**Comment by gennei** [comment]
LGTM:+1:

**Comment by ksato9700** [comment]
イイですね〜 :+1:

**Comment by kskktk** [comment]
急で申し訳ないですが、OSCに関するオンラインMTGをやりたいと思います。
今日明日の夜（深夜にはならないくらい）の時間で候補時間を出していただけませんか？
ツールは何でもいいですけど、Skypeが一番いいですかね？

僕は今日明日と18時以降であればオッケーです。
どうぞよろしくお願いします。

**Comment by takahashim** [comment]
@kskktk ちょっと遅めですが今日は21時〜とかなら参加できます。
明日は18時〜でも大丈夫そうです。

**Comment by gennei** [comment]
@kskktk 今日の21時からであれば可能です。

**Comment by kskktk** [comment]
@cognitom @nanbuwks いかがでしょうか〜？

**Comment by nanbuwks** [comment]
Chatでよければ、本日22時以降、明日なら18時〜20時であればOKです。

**Comment by kskktk** [comment]
みなさん
22:30とかいかがでしょう？
2015/10/22 21:39 "nanbuwks" notifications@github.com:

**Comment by takahashim** [comment]
:ok_woman:

**Comment by gennei** [comment]
:ok_hand:

**Comment by nanbuwks** [comment]
了解です

**Comment by cognitom** [comment]
:+1:
@kskktk さん、すみません反応遅れました。とりあえず、Slackにいまーす。

**Comment by kskktk** [comment]
すみません。skype id教えて下さい
2015/10/22 22:16 "nanbuwks" notifications@github.com:

**Comment by takahashim** [comment]
@kskktk あー、slackでもよいですか？
念のため、skype idは masayoshi.takahashi です

**Comment by nanbuwks** [comment]
僕の skype id は nanbuwks です。　slackもオープンしています。

**Comment by takahashim** [comment]
出展どうもおつかれさまでした！　セミナーの方も部屋の大きさからいってちょうどいいくらいに人が入っていてよかったです。

次のイベントはシャッカソンですね。こちらもよろしくお願いいたします。

**Comment by gennei** [comment]
こちらのIssueはひとまず Close して問題無いですかね？

**Comment by kskktk** [comment]
closeする前にslackとの連携テスト

**Comment by kskktk** [comment]
特に問題なさそうなのでcloseしますねー
