### ISSUE TITLE
OSC 2016 Tokyo/Spring への出展

### ISSUE THREAD

**Issue by nanbuwks** [aozorahack/aozorahack#33]
2月26日(金)-27日(土)開催の OSC 2016 Tokyo/Spring の出展申込が開始となっています。
http://www.ospn.jp/osc2016-spring/
申込期限は【12月21日(月)】です。

OSC 2015 Tokyo/Fall の出展が好評だったこともあり、次回も出すべし、と思ってますがいかがですか？

**Comment by nanbuwks** [comment]
締め切りが迫ってきました！ とりあえず、僕から申請出しておきましょうか？

**Comment by takahashim** [comment]
@kskktk どうしますか？（私は出展していいんじゃないかなーと思っております）

**Comment by kskktk** [comment]
すみません。全く気付いておらず！こちらはエントリーしておきます！

**Comment by kskktk** [comment]
エントリーしました。ただし日程は土曜日のみ（初日の金曜日がウィークデーで人員確保が難しそうであるため）です。

**Comment by nanbuwks** [comment]
今回も僕の出展団体「秘密結社オープンフォース」と隣接希望出しておきましょうか？　金曜日も僕は出展するので掛け持ちでよければ金曜日パンフ配布ぐらいは可能です。

**Comment by nanbuwks** [comment]
エントリーは展示・セミナー両方？
