### ISSUE TITLE
コミックマーケット９０ 2016夏コミ にサークル参加しませんか？

### ISSUE THREAD

**Issue by nanbuwks** [aozorahack/aozorahack#34]
OSC 2015 Tokyo/Fall に、大久保ゆうさん翻訳のピーターラビットなどを印刷製本し頒布したのが割と好評だったというのがあります。こんな感じで薄い本を作って無料頒布するなり販売するなり、いかがでしょう。
既に公開されているテキストをそのまま印刷するのも良し、表紙や挿絵をパブリックドメインなところで独自に作って組み合わせるのも楽しいかなと。
エンジニアリングに関する薄い本も作りたいけど、まだ機は熟していないかな・・・

**Comment by kskktk** [comment]
コミケについては、正直なところ僕に意見はありません。ただ結構大変そうだなぁという気も。みなさんはどうでしょう？

**Comment by nanbuwks** [comment]
最初のサークルエントリーはほぼ当選しないことを見越して、今回はとりあえず出すだけ出すというのも手ですね。エントリー費用￥10000ぐらいかかりますが。なお、当選しなかった場合は￥8000は返ってきます。

**Comment by kskktk** [comment]
本件ですがいろいろ考えて以下の条件ならコミケに出しても良いかと考えました

サークル名に「aozorahack」を使う場合は
- aozorahackや青空文庫に関係するもののみの出展に限定（委託は原則受けない）
- ブースには会期中必ず常に誰かいるようにする（告知が目的なので）

どうでしょうか？

**Comment by nanbuwks** [comment]
出展枠ですが、ジャンルコードを決めないといけません。「評論・情報」(コード135)ないし「同人ソフト」(コード240)あたりかなと思います。
http://www.comiket.co.jp/info-c/C90/C90SubGenre.html
青空文庫で考えれば「評論・情報」(コード135)が最も近いですが、システム開発という側面、またITエンジニアへのJoinを目指すなら「同人ソフト」(コード240)に出すのが妥当かと考えます。「同人ソフト」はサーバ／インフラ／サービスなどの研究報告もここでなされており、コアな方々との交流が見込まれます。
さて、僕は事前準備協力できますが、別のブースに詰めることになりそうでその場合aozorahackブースに詰めることはできませんがどうでしょう。それでもよければ申し込み書を取り寄せます。（取り寄せは今日中）

**Comment by kskktk** [comment]
一応僕も申込書を取り寄せています。ただ当日店番がいないとなると難しそうなので、今回は見送りとさせてください。他に出したいという方がいればおしらせください。

**Comment by nanbuwks** [comment]
2/10締め切りですね。特に他に出したい方がおられなければ、申込書僕が買い取りましょうか？
