### ISSUE TITLE
aozorahack.org サイトを準備する

### ISSUE THREAD

**Issue by takahashim** [aozorahack/aozorahack#35]
本の未来基金さんの方でaozorahack用に aozorahack.org というドメインを取得していただいたそうなので、github pagesでホストするようにしたいのでした。
- [x] レポジトリ用意する
- [x] コンテンツ用意する
- [x] DNS設定してもらう

**Comment by takahashim** [comment]
とりあえず「aozorahack.org」という名前のレポジトリを作るのがよいでしょうか。

**Comment by gennei** [comment]
:+1:

**Comment by takahashim** [comment]
なお、サイトを用意する目的としては、青空文庫や本の未来基金の関係者の方から「aozorahackでいろいろ活動していることは興味があるけれど、さすがにgithubを見て活動を把握するのはハードル高いので、もうちょっと分かりやすく動きを紹介する場所を用意してほしい（＜ @kskktk さんから聞いた話を意訳）」ということだそうです。
なのでMarkdownとかで書いた情報をHTMLに変換して載せておくくらいで最低限の要求は満たせそうかと思っています。

**Comment by takotakot** [comment]
初めまして。私も、青空文庫のサーバ老朽化…の話から、どういう動きがあるのかな、と思っていたので、そういうサイトがあると、見た目に分かりやすいと思います。

というか、PostgreSQL のサーバをどうするか…という話は今どうなっているのか、分かりますか？

**Comment by takahashim** [comment]
@takotakot DBについては、とりあえず現状はバックアップはとられているようなので何かあっても復旧は可能、という話が以前出てました。とはいえ、物理サーバ自体は以前から稼働していたものがそのまま使われているようです。

今後については今度のOSCで何かしら話せる予定です（最近私の方でもちょっと暗躍していて、その辺の情報を出せることになりそうなのです）。

**Comment by kskktk** [comment]
お返事おそくなって申し訳ありません。高橋さんがご説明いただいている内容のとおりです。

**Comment by takahashim** [comment]
まずはレポジトリ作りました。
https://github.com/aozorahack/aozorahack.org

**Comment by takahashim** [comment]
すみません、Organization siteなので
https://github.com/aozorahack/aozorahack.github.io
にrenameしました。

@kskktk  CNAMEファイルは用意したので、aozorahack.orgのDNSの設定で、Aレコードに192.30.252.153と192.30.252.154を設定してもらえますか？

**Comment by kskktk** [comment]
@takahashim 上記設定しました。TTLはとりあえず3600にしています。

**Comment by takahashim** [comment]
@kskktk ありがとうございます、見れました！
コンテンツの方はどうしましょうか…。

**Comment by kskktk** [comment]
なんか参考になりそうなページとかってありますか。もしよかったら教えていただけると。

**Comment by takahashim** [comment]
これ、というのが思いつかないんですよね…。

**Comment by takahashim** [comment]
強いて言えば、Code for X方面とかでしょうか。日本語じゃないですが Code for America http://www.codeforamerica.org/ とか、g0v.tw http://g0v.tw/en-US/index.html とかですが、ちょっと大きすぎるような。
Code for Kanazawa http://www.codeforkanazawa.org/ くらいのサイズが手頃でしょうか。項目としては、 Home / About / Projects / How to Join くらいで。

**Comment by spiegel-im-spiegel** [comment]
個人的にはここの Issues や他の repository の内容や進捗を集約した記事とかあると嬉しいです。週刊か月刊くらいで。

**Comment by takahashim** [comment]
@spiegel-im-spiegel 定期更新はちょっと大変そうですが（月刊ならなんとかなる？？）、更新情報的なページはあってもよいかもですね。

**Comment by kskktk** [comment]
そうですね。月一とか、あるいは何か大きな動きがあった時にレポートするというのはできそうですね。

**Comment by kskktk** [comment]
内容はまずはOSCに向けてチラシの内容を移植して、slackinへのリンクを貼る感じにするのはいかがでしょう。
![aozorahack](https://cloud.githubusercontent.com/assets/2081248/13204253/9aa74f54-d90e-11e5-9110-7cacca16a554.jpg)
![aozorahack_ura](https://cloud.githubusercontent.com/assets/2081248/13204254/9bdedf04-d90e-11e5-8fde-532201fd8321.jpg)

**Comment by kskktk** [comment]
デザインはとりあえずめんどくさいので、bootstrapか何かを使う感じですかね……。あるいはペライチでざくっと作ってしまうか。

**Comment by spiegel-im-spiegel** [comment]
:+1:

**Comment by kskktk** [comment]
bootstrapもめんどいので、とりあえずローンチは↓でやっちゃうというのもありですかね
http://orderedlist.com/minimal/

**Comment by takahashim** [comment]
まあbootstrapで作ってしまいましょうか。
チラシのテキスト素材はどこかにありますか？

**Comment by kskktk** [comment]
# 青空文庫をハックしたいひと、募集中

#aozorahack

著作権切れのテキストを中心に、今や1万3000作品の自由な電子本を収蔵する日本最大級のインターネット電子図書館「青空文庫」。青空文庫の運営はボランティアによって受け継がれてきました。1997年のスタートから着実に蔵書数を増やしてきましたが、だんだんとそのシステムは古くなってきてしまいました。

そこで青空文庫を技術の力で支えようとスタートしたのが #aozorahack です。青空文庫とは協業関係にあり、本の未来基金の支援を受けています。当面の目標はサーバの安定運用とシステムの分散ですが、それ以外にも青空文庫が今後も続いていけるようなしくみをみなさんと一緒に考えて、動かしていければと考えています。

どうかあなたの力を貸してください。興味本意でも全然OK。まずはGitHubでコメントをください。もしなにかご質問がありましたら下記のメールアドレスまでお気軽にご連絡ください。

aozorahack@honnomirai.net

Book by Samuel Q. Green from the Noun ProjectCloud by Viktor Fedyuk from the Noun Project (CC BY 3.0 US)
https://thenounproject.com/term/book/4080/
Cloud by Viktor Fedyuk from the Noun Project (CC BY 3.0 US)
https://thenounproject.com/term/cloud/166562/
About CC Lisence : http://creativecommons.org/licenses/by/3.0/us/

**Comment by kskktk** [comment]
# aozorahackがめざすもの

## 青空文庫を長く使えるように

青空文庫はサーバの増築を繰り返して発展してきました。しかし青空文庫のボランティアの人たちが使う「作業着手連絡システム」（チケット管理やバージョン管理、バグトラッキングを包括する青空文庫独自のウェブアプリ）を収容するサーバの老朽化が問題となっています。そこで #aozorahack ではそのサーバをまずは保護し、新しい環境で動かせるような手当てを進めています。また作業着手連絡システムをより使いやすくすることも考えています。

## 青空文庫にもっとたくさんの電子テキストを

青空文庫に収蔵されているテキストは世界中にいる青空文庫のボランティアが入力しています。ただ入力が終わったからといってそのままテキストを公開するわけではありません。ボランティアから送られてきた電子テキストを元の本と照らし合わせて誤りがないかをチェックする校正作業を経てから、やっと公開となるわけです。この入力と校正の作業がより楽なものになれば、もっと青空文庫に電子テキストを増やすことができます。#aozorahack ではこの作業をより簡単にする技術的なしくみを考えていきます。

## 青空文庫をもっとおもしろく

青空文庫にはたくさんの電子テキストがあります。青空文庫を通して、思わぬ本との出会いが生まれるかもしれません。また青空文庫のテキストをビッグデータとして利用し、新しい何かが生まれることができるかもしれません。そのためには青空文庫をもっとたくさんの人に使いやすく提供することが必要です。#aozorahack では現在の青空文庫に新しい機能を付け加えたり、さまざまなデータ形式で本へのアクセスができるようなしくみを考えていきます。

## 今後の予定

まずは課題の作業着手連絡システムの移転に注力します。連絡にはSlackとGitHubを使っていますが、今後は月イチのミーティングを考えています。オンラインでも参加できるようなかたちで運用します。また来年の夏には本の未来基金の大きなイベントを考えており、その中で何らかの#aozorahack のイベントを考えています。

GitHub: https://github.com/aozorahack/aozorahack
Slack: https://aozorahack.slack.com
E-mail: aozorahack@honnomirai.net

**Comment by takahashim** [comment]
@kskktk :ok_woman:

**Comment by takahashim** [comment]
とりあえず更新しました。
文面は見直した方が良さそう…。

**Comment by takahashim** [comment]
とりあえずサイト自体はできたので、こちらのissueは閉じて、続きは https://github.com/aozorahack/aozorahack.github.io/issues で行うということで。
