### ISSUE TITLE
オープンソースカンファレンス2016 Tokyo/Spring

### ISSUE THREAD

**Issue by kskktk** [aozorahack/aozorahack#36]
日程：2016年2月26日(金) 10:00～18:00（展示：11:00～17:30）
　　　　　　 2月27日(土) 10:00～17:30（展示：10:00～16:00）
会場：明星大学 日野キャンパス 26号館 2F(OSC受付)

aozorahackは土曜日のみ出展します。
土曜日の12時からセミナーもあります。
お手伝いをいただける方を募集しますー。

**Comment by kskktk** [comment]
# OSC tokyo 2016/springもろもろ

## 重要情報

学内のコンビニは春休みで休業中!
必要なものは駅降りてすぐのファミマで買っていきましょう。

## 参加者

高橋、河野、香月、宇谷
（他の人もブースに遊びに来てください！ステッカー差し上げます）

## タイムスケジュール

9:00：香月・宇谷会場入り、設営
10:00：展示スタート
11:45：展示一旦ストップ、セミナー会場へ
12:00~12:45：セミナー開始
13:00~16:00：展示引き続き
終了後撤収して解散
（昼食は適宜交代でとりましょう）

## セミナー

12:00~12:10 / 全体説明（香月）
12:10~12:30 / 調査結果報告と今後の話（高橋）
12:30~12:35 / 青空文学部（河野）
12:35~12:45 / 落ち穂拾い、質疑応答
セミナー後のアンケートは特に必要ないかと思いますが、いかがでしょう？

## 展示

### 展示物
- チラシ
- 前垂れポスター
- ステッカー
- その他個人の持ち物で青空文庫関連のもの
  - Kindle, 青空文庫の本など
  - 香月預りの河野さん作成の本は持って行きます！

**Comment by takahashim** [comment]
参加されたみなさまおつかれさまでした！
私の発表資料は以下におきました。
http://www.slideshare.net/takahashim/osc-2016-tokyospring-aozorahack

**Comment by gennei** [comment]
イベント完了しているのでクローズします。
