### ISSUE TITLE
中国国内に「青空文庫」のmirror siteを作りたいですが　どうすればいいでしょうか

### ISSUE THREAD

**Issue by xisang233** [aozorahack/aozorahack#39]
私はエンジニアではなく、ただの日本語学部の生徒です。中国からは時々繋がらないので、困っている人が少なくはないと思います。前から、中国のサーバーでもう一つ「青空文庫」のサイトを作れば中国の使用者も楽に使えると思います。
　昨日の夜info@aozora.gr.jpにも送信してみました。どこに送信すればいいか分からないですので、ここにも送信してみました。

**Comment by takahashim** [comment]
遅いお返事ですみません。
ちょっと期待されている回答とは違うかもしれませんが、青空文庫サイトにつながらない場合でも、 githubにつながるのであれば https://github.com/aozorabunko/aozorabunko からファイルを持ってくることは可能かと思います。

**Comment by xisang233** [comment]
え、、、ちょっとわからないのですが。
「違うかもしれない」とは　どういうことでしょうか。
https://github.com/aozorabunko/aozorabunko　の内容を全部git cloneすれば　ミラーサイトを作ることができるのでしょうね。どうして「違う」のですか。
著作権存続とかの原因でしょうか。

**Comment by takahashim** [comment]
@xisang233 cards/*/filesディレクトリの下にあるzipファイルやHTMLファイルについては自由に加工・再配布可能ですが、それ以外のファイルについてはどういう条件で使っていいのかよく分からないので、ローカルの閲覧のみにしておいた方がよいかもしれません。

**Comment by xisang233** [comment]
分かりましたが、プログラムとか　本以外のファイルは勝手に使ってはいけないということですね。
両国の法律に注意しながら使い方に工夫して、みんなが青空文庫を自由に使えるように頑張ります。

**Comment by ekzemplaro** [comment]
xisang233 さん、今晩は。私はエンジニアです。協力させて下さい。
まず、ミラーサイトと、コピーサイトは異なります。ミラーサイトとは、鏡のようにそのまま写したものです。コピーとは、似たように移したものです。ミラーサイトを作るには、データベースのダンプなどが必要ですが、それは青空文庫から提供されるのは期待できません。
コピーサイトはすでに、存在します。
https://archive.org/details/aozorabunko
ただし、かなり欠落があります。
コピーサイトを、中国に作られたら良いと思います。
あと、録音音声が、librivox.org に少しあります。Japanese で検索してみて下さい。これらも、日本語の学習に役に立つと思います。

以上。

**Comment by sgqy** [comment]
http://www.aozora.gr.jp/ このサイトはデータベースを持っているダイナミックなサイトだと思います。
そしてこの repo https://github.com/aozorabunko/aozorabunko は毎日 07:00 JST で push されています。

去年 Aliyun の VPS を買ってみました。git-bash で、スクリプトをループし、毎日サイトを更新しました。
ですが SSL は必要だと思います。

github.com から自分の VPS への通信は暗号化必要。(ssh-key or https)
VPS から利用者への通信も暗号化必要。(https)

その本たちは青空文庫そのものだと思います。だから偽ミラーを作ってもいいでしょう。

**Comment by ekzemplaro** [comment]
sgqy さん、こんにちは。
まさしく、その通りです。PostgreSQL を使っています。
PostgreSQLのデータが、簡単にインポートできる形で公開されていないので、データベースのミラーが作れないのです。
CSV から、作るとしたら、データの正規化ということをしなければなりません。

以上。

**Comment by xisang233** [comment]
ええと。。。
私は日本語学部なので、技術のことはあまり分からないの手セスが、、、
@sgqy @ekzemplaro わざわざ返事してありがとうございます。そこまで複雑に考えませんでしたので、もっと検討しなければならないと思います。
私は少しだけPythonとCができます。Linuxを日常使っていますが、簡単なものしかできません。一人の力でサイトを作るのは無理です。

**Comment by xisang233** [comment]
@sgqy 不是有个青空转epub的java程序？我想的是不光弄成一个方便墙内基友(包括我233)的玩意，最好还弄出来一些别的功能。
(做一个アオアオ23333)

**Comment by ekzemplaro** [comment]
xisang233 さん、おはようございます。
私も、Linux を使っています。今、この文章もLinux で書いています。Python は、私の得意言語です。一人では、大変でも力を合わせればなんとかなります。やってみましょう。

以上。

**Comment by sgqy** [comment]
@xisang233 https://github.com/hmdev/AozoraEpub3 这玩意吧（
前两天为 syosetu 网站上的小说制作过 kindle 上用的 mobi 格式，手动。当时见到了这玩意不过没仔细看说明不知道它支持 mobi（
不过还是针对它的 txt 用 boost 库写了个转换器……

japanese:
https://github.com/hmdev/AozoraEpub3 このツールなんでしょうか。
先日「なろう系」の小説を手作りでキンドルのmobiを作ってみましたのは、そのプロジェクトの説明を読まないせいだったですｗ。
boost で txt -> html の converter を実現しましたが…

**Comment by xisang233** [comment]
@ekzemplaro はははは、これも海の彼方の縁ですね。私はどちらも簡単な操作だけできないですけど

**Comment by xisang233** [comment]
就是这个。
在服务器上安装一个，让服务器端实现网页请求 -> 在线转码怎么样，我觉得这样会方便kindle和各种爪机。(类似Aozorakindle，但是我不觉得文科生会聪明到加收藏夹然后直接点收藏夹里面的js2333)
光是copy一个站过来多没意思，不如搞点有意思的。

そうです
AozoraEpub3をサーバーにインストールして、mobiを作る機能を実現したらどうでしょうか?
ユーザーがwebでボタンをクリック->サーバーがmobiを作る->ユーザーがダウンロードする。
kindleとかスマホとかのユーザーがもっと便利に利用できるでしょう。
青空キンドルと似ているのですが、もっと操作が簡単だし　便利になれると思います。
新しいサイトを作れば　やはり新しいものを試したほうがいいと思います。

**Comment by takahashim** [comment]
@sgqy www.aozora.gr.jp 自体はstaticなサイトのはずです。このサイトとは別に、DBを持ったサイトがあって、そこでHTMLを生成し、それをバッチで毎日 www.aozora.gr.jp に転送しているそうです。

また、青空文庫 Revised http://aozora.textlive.net/ というサイトでも、AozoraEpub3によるEPUBの配布を行っているみたいでした。

**Comment by xisang233** [comment]
http://aozora.textlive.net/
 このサイトのほうが　もっと便利だろうと思います。遅いけど

青空読手も利用しているのですが、少しだけ「残念」な思いをしてしまいます。「中国の習慣に合う(良くない習慣ばかりけど...)」　このようなサイト+アプリを作りたいです。
自分の意欲から発足し、ちょうどみんなもそう思っている。このようなもののほうがもっと理想的じゃないでしょうか。
でもね、すぐに完成するわけにはいかないですね。「慌てない慌てない　一休み一休み～」

**Comment by ekzemplaro** [comment]
こんにちは。
您好。

まずは、小さく作って、大きく育てていったらどうでしょうか。例えば１０冊に限定して、テキストと、epub を提供するとか。

参考として、私がメインテナンスしている LibriVox （オーディオブック）のカタログシステムを紹介します。
http://ekzemplaro.org/librivox/catalog/
最初のアクセスは、データを総てダウンロードするので時間がかかります。でも、ダウンロードしてしまえば、総てクライアントで処理をするので速いです。
Japanese を選択して頂ければ、３７冊の日本語タイトルがでてきます。ほとんどは、青空文庫にテキストがあります。

以上。

**Comment by xisang233** [comment]
@sgqy
让我一个只会git clone的亚历山大呀

**Comment by sgqy** [comment]
确实有难度。你说的东西其实是一个webapp：“在静态页面里加入一个动态打包的功能”。
这里有个概括介绍：http://www.vaikan.com/how-to-develop-web-applications/
既然会玩linux和python可以选用python的web框架。

**Comment by xisang233** [comment]
ええと、まずは言語を決定しましょうか。python2か3か、python+djangoかphpか、一つ選ぶのも私には難しいです。pythonが得意だとエンジニアさんは言ったんですね、三人とも日本語ができるから Rorも悪くない選択だと思います。

素人なので、私はどれでもいいと思います。どれでも最初から勉強しなければならないですから。

**Comment by ekzemplaro** [comment]
おはようございます。
Ruby on Rails がいでしょう。日本に限定すれば、ruby の方が、python より使い手が多いですから。それに、lisp と較べれば、python と ruby は似たようなものですから。

以上。

**Comment by xisang233** [comment]
@ekzemplaro 
やっとMintでrails5.0.0をインストールしました。何度も繰り返して、大変な二日でした。直截にapt-getするのもできるけど、私の買ったrailsの本はrails　5.0.0で、apt-getできなかったです。。。これからは、Rorを勉強します。
JSとかHtmlとか手伝ってくれる方はいるでしょうか?

**Comment by xisang233** [comment]
やはり jsをもっと活用しなければね。
私はこの前、jsの能力をはっきり見えなかったです。

**Comment by ekzemplaro** [comment]
今晩は。
js というか、jQuery ですね。jQuery は、js のライブラリーです。Node.js もなかなかいいですよ。
Node.js は、コンソールで使える js です。

以上。

**Comment by xisang233** [comment]
それじゃ まずはRorにしますね。

**Comment by xisang233** [comment]
jsとnode.jsを間違いました､

**Comment by xisang233** [comment]
半年前の続きです。。。
昨夜一晩中　AozoraEpub3 と KindleGen を使って、githubからダウンロードした.zipファイルを全部epubとmobiに転換しました。データーベースと連続するなど、もう少し準備すれば、一応使えるようになると思います。
ただ著作権存続のファイルは特別に処理しなければならないのですね。

**Comment by ekzemplaro** [comment]
xisang233 さん
こんにちは。
着々とすすんでいますね。
ある程度できたら、ベータテストを始めましょう。
応援します。

以上。

**Comment by xisang233** [comment]
いろいろな方法を考えた最後　csvファイルがあることに気づきました。
csvファイルだけで十分だと思うんですが。

今、考えがちょっと変わったのです。ミラーサイトではなく、ただ「便利にmobiファイルをキンドルに送信する」ことができるものを作りたいと思います。今は自分のパソコンで実現したんですが、ほしい本があれば自分で探すしかありません。csvファイルを利用すれば、簡単なwebアプリが作れると思います。
