### ISSUE TITLE
OSC2016 Tokyo/Fall

### ISSUE THREAD

**Issue by nanbuwks** [aozorahack/aozorahack#40]
日程：2016年11月5日(土) 10:00～18:00（展示：11:00～17:30）
　　　　　　 11月6日(日) 10:00～17:30（展示：10:00～16:00）
会場：明星大学 日野キャンパス 28号館
http://www.ospn.jp/osc2016-fall/
団体・コミュニティ・企業 出展受付中（9月5日締切）
来年の武道館開催につなげるためにも今回も出しましょう！　展示およびセミナーで申し込みしませんか？

**Comment by takahashim** [comment]
そういえばこれってどうしましょうか…？ @kskktk

**Comment by nanbuwks** [comment]
明日締め切りですね。
・今回は土日開催なのでフルで出したい
・前回は金土開催で土曜日だけの出展にしたら他団体と２コイチブースになったのでそれは避けたい
・青空文庫ステッカー再度配布したい
・セミナーは割と受講者多いので関心は高い
・ハッカソンの成果をセミナーで発表したい
・継続して出すというだけでも意味はある
・ハッカソン・シャッカソン・OSCなどの出展を定常的に回していくことがエンジニアへの浸透を図る方策の路線としてやっていくのでいいのではないか

**Comment by nanbuwks** [comment]
なお、僕は「秘密結社オープンフォース」名義で出展します。隣接ブースで申請いただいたら前回・前々回のように＋α効果を見込めるかも知れませんが、近隣ブースのジャンルが偏るので出展要員が十分ならあまりこだわらなくてもいいかもしれません。

**Comment by nanbuwks** [comment]
僕が申し込みしておきましょうか？ 同じ人間で複数申し込みすると2コイチブースになる可能性が高いので別の人間が申し込むのが望ましいですが。
もし今日の夜までに特に意見がなければ、「aozorahack」で合意が不足ということで「青空文学部」名義を使って僕から出しておきます。

**Comment by kskktk** [comment]
ごめんなさい。寝込んでおりこちらを全然チェックできておらず……。
@nanbuwks さん、申し込み書のフォーマットってお持ちですか？
今事務局にはフォームから連絡したのですが、もしあれば記入作業を始めたいなと思っております。

**Comment by kskktk** [comment]
事務局よりxlsが届いたので今から記入します

**Comment by nanbuwks** [comment]
登壇の記入のところ、「同時間NGの団体等」に秘密結社オープンフォースとしておいていただけるとありがたいです。

**Comment by kskktk** [comment]
はい。その記入は終わりました。あとはセミナー時間を決めるだけなんですけど、日曜日にしようと思っています。

**Comment by kskktk** [comment]
@gennei @takahashim 日曜日の希望時間とかありますか？ なければ僕で昼の時間帯に入れてしまいますが。

**Comment by gennei** [comment]
@kskktk 
いつものようにお昼の時間で問題ないと思っております。

**Comment by takahashim** [comment]
@kskktk @gennei お昼でよいですー

**Comment by kskktk** [comment]
応募完了しました！ リマインドしてくださった @nanbuwks @takahashim ありがとうございました

[OSC2016_TokyoFall_community_Appli.xlsx](https://github.com/aozorahack/aozorahack/files/454819/OSC2016_TokyoFall_community_Appli.xlsx)

**Comment by nanbuwks** [comment]
内容考えていかないといけないですね。
・発表者はいつもの3名？
・展示は青空ハッカソンの成果物を出していきませんか？
・今回こそ、セミナー時のアンケート取りませんか？

**Comment by takahashim** [comment]
https://www.ospn.jp/osc2016-fall/modules/eguide/event.php?eid=61 セミナー枠、日曜の昼になったようです。

発表者は他にも発表したい人がいれば追加してよいかと思います。

> 展示は青空ハッカソンの成果物を出していきませんか？

いいと思います！

> 今回こそ、セミナー時のアンケート取りませんか？

何か取りたい項目はありますか？

**Comment by takahashim** [comment]
こちらは閉じておきますね
