### ISSUE TITLE
リポジトリ作成依頼 「aozorabot」「aozora.js」

### ISSUE THREAD

**Issue by ksato9700** [aozorahack/aozorahack#41]
Slackの上で動くbotを試作してみたので、そのソースコードを格納する「aozorabot」と、そこで使っているJS/CoffeeScriptのライブラリを格納する「aozora.js」の作成をお願い致します。

**Comment by kskktk** [comment]
作りましたー

**Comment by ksato9700** [comment]
早速有り難うございます 👍
