### ISSUE TITLE
どうして2016年11月からのアクセスランキングがないのでしょうか

### ISSUE THREAD

**Issue by xisang233** [aozorahack/aozorahack#43]
http://www.aozora.gr.jp/access_ranking/
最新のデータ（例えば去年一年中の）を見たいのですが。。。どこでみられるでしょうか。

**Comment by kskktk** [comment]
ここのデータはプログラムで自動で作成されていないためです。現在青空文庫の方が作業をされていると思いますのでもうしばらくお待ち下さい。（将来は自動化したいですね……）

**Comment by xisang233** [comment]
ほかにもデーターを見られる場所はありますか。。。

**Comment by kskktk** [comment]
今のところ外部からみることはできないはずです、残念ながら……

**Comment by xisang233** [comment]
では、待ちます。
ご迷惑をかけてすみません。

**Comment by kskktk** [comment]
いえいえ、全く迷惑なんかではありません。今後もなにか気付いたことがあったら教えてください。谢谢！
