### ISSUE TITLE
同人誌作成用レポジトリを作る件

### ISSUE THREAD

**Issue by takahashim** [aozorahack/aozorahack#44]
Slackの方で同人誌を作りたいという話が出ているので、githubの方にレポジトリを作りたいと思っています。以下引用です。

* 青空文庫20周年イベントに連なるaozorahackイベントを秋に行います
* そこで配布する薄い本を作成しましょう
* 配布形態は印刷製本・コピー本・電子データ・その他のうち、どうするかは後で考える
* ちゃんとした本にするとめんどくさいので「薄い本」で
* 内容はaozorahackで出すのでテクノロジーめいたところをからめて
* アンソロジーみたいにするか、Wikipediaみたいに集合執筆にするかは意見を募って考える
* ライセンスはPublic Domain/CC0で

ちなみに背景として、青空文庫は1997年開設なので、2017年の今年でめでたく20周年だそうで（参考：[青空文庫の提案](http://www.aozora.gr.jp/cards/001790/files/56572_51810.html)）、20周年記念イベント的なことを計画されているそうです（香月さん談）。それはそれとして、aozorahackでも何かやれるといいですねという話になっています。

**Comment by nanbuwks** [comment]
レポジトリ名 20thdoujinshi でどうですかね。

**Comment by takahashim** [comment]
https://github.com/aozorahack/20thdoujinshi
了解です、ということで 20thdoujinshi で作りました
