### ISSUE TITLE
リポジトリ作成依頼 (pubserver2, db_importer)

### ISSUE THREAD

**Issue by ksato9700** [aozorahack/aozorahack#45]
[Pubserver](https://github.com/aozorahack/pubserver)はCoffeescriptという言語で実装していましたが、言語としてあまりポピュラーではなく、同時にJavaScriptがだいぶ言語拡張され利用しやすくなってきたので、最新のJavaScriptでPubserverを再実装し始めています。その為のリポジトリをAozorahackに欲しいと考えています。同時に、情報をDB投入するためのスクリプトも分離して別リポジトリとしたいと考えています。したがって、以下のリポジトリを作っていただけないでしょうか。

aozorahack/pubserver2
aozorahack/db_importer

よろしくお願いいたします。

**Comment by takahashim** [comment]
なるほどリポジトリ分割するんですね。了解です！

**Comment by takahashim** [comment]
@ksato9700 とりあえず管理権限つきで2つ作ってみました。これでよいでしょうか？

**Comment by ksato9700** [comment]
早速作っていただきありがとうございます！
