### ISSUE TITLE
もう一つの入力作業方法の可能性

### ISSUE THREAD

**Issue by xisang233** [aozorahack/aozorahack#46]
先日スキャナーとOCRソフトを使ってみれば想像以上に識別力が高かったです。スキャナを使って直接原本をスキャンすることは試したことがありますか。

**Comment by takahashim** [comment]
どのくらいの比率で使われているかはわかりませんが、青空文庫作業マニュアル【入力編】【校正編】でそれぞれOCRに触れられているくらいですし、一定数は使われているようです。

https://www.aozora.gr.jp/aozora-manual/index-input.html#input
https://www.aozora.gr.jp/aozora-manual/index-proofreading.html#proofreading04

**Comment by ksato9700** [comment]
ライセンス的にどうなのかちょっと微妙なのですが、Google Driveに文字を含む画像/PDFをアップロードし、「アプリで開く」→「Googleドキュメントで開く」とすると、現代文であれば結構な精度で文字認識してくれます。旧字体などを含む場合、どれくらいなのかは正直やったことがないのでわからないのですが…
