### ISSUE TITLE
青空文庫関連ツールのリスト

### ISSUE THREAD

**Issue by cognitom** [aozorahack/aozorahack#5]
[追記] [tools.md](https://github.com/aozorahack/aozorahack/blob/master/tools.md)に置くことになりました。追加がある場合は、そちらを変更してPRを送ってください。

---

Wikiに移した方がよいかもですが、話題に上がった/気になったツールを並べていきます。コメントもらったら追記しますね。
## テキスト変換スクリプト
- 公式ツール [txt2xhtml (青空文庫 組版案内)](http://kumihan.aozora.gr.jp/slabid-14.htm) - [Google Code](https://code.google.com/p/aozora-collection/source/browse/) - Ruby
- [青空文庫テキスト→ePub3変換](https://github.com/hmdev/AozoraEpub3/) - Java
- [Aozora-bunko ruby parser](https://www.npmjs.com/package/aozora-ruby-parser) - JavaScript
## 入力・校正関係
- [結城さんによる「青空文庫の応援ページ」](http://www.hyuki.com/aozora/) - 旧字体置換可能チェッカー「校閲君」ほか
## 外字関連
- [グリフウィキ・青空文庫外字](http://glyphwiki.org/wiki/Group:%E9%9D%92%E7%A9%BA%E6%96%87%E5%BA%AB%E5%A4%96%E5%AD%97)
- [漢字データベース](http://kanji-database.sourceforge.net/aozora/gaiji.html)
- [青空文庫に出現する外字注記とUCSの対応一覧](https://github.com/cjkvi/cjkvi-data/blob/master/aozora_gaiji_chuki.txt)

**Comment by takahashim** [comment]
txt2xhtmlは、Google Codeよりもkumihan.aozora.gr.jpの方は良さそうです（公式の配布元なのと、その他の配布ファイルもあるので）

**Comment by cognitom** [comment]
@takahashim 両方にリンクを付けていたんですが、見にくかったですね。調整しました。もう少し集まったら表組みにした方がよいかも。

**Comment by takahashim** [comment]
う、すみません、見落としてました… :bow:
Wikiにするか、GitHub PagesでWebサイトを用意するかになるんじゃないかと（pull requestベースの方が、変更点や変更の経緯が追いかけやすくて良いかなあ、という気持ちもあります）

**Comment by key-amb** [comment]
おぉ、こういうまとめありがたいです。
Wiki でも gh-pages でもどちらでもいいですが、前者は編集・更新が楽、後者は履歴管理しやすいってとこですかね。
楽な方から始めて移したくなったら移すのでもいいかと。

**Comment by cognitom** [comment]
Wikiとgh-pagesの中間をとるような感じで、tools.mdを設置しましたので、以降はそちらによろしくです ;)

**Comment by ksato9700** [comment]
OCRツールに関する情報をまとめておきたいなと考えていたのですが、「青空文庫関連ツール」に入れて良いのか迷っています。tools.mdに入れても良いでしょうか？

**Comment by takahashim** [comment]
@ksato9700 とりあえず入れてみていただいて、違いそうだったら分割するなり他の方法を考える感じで良いかと思います！  :smiley_cat:

**Comment by ksato9700** [comment]
早速有り難うございます。
了解しました。ではその様にさせていただきます。
