### ISSUE TITLE
雑談用にGitter作りませんか?

### ISSUE THREAD

**Issue by cognitom** [aozorahack/aozorahack#6]
Issueだと、構えてしまう/書きにくいこともあるかと思うので、雑談OKなGitter作っておきませんか?
https://gitter.im/

(Facebookグループとかでも構わないです。IRCは最近使わなくなってきたかな...)

**Comment by takahashim** [comment]
@kskktk さんはslackを用意すると言ってました（が、個人的にはチャットはあんまり使わないので使いたい方にお任せな感じです）

**Comment by cognitom** [comment]
了解、slackでよいと思います。

**Comment by kskktk** [comment]
slackなのは僕が普段使っているからなので、使いやすければgitterでもいいと思います。皆さんはどっちの方がいいんですかね。

**Comment by cognitom** [comment]
Gitterは、コードブロックでGitHubと同じシンタックスハイライトができるのは便利ですね。

Slackで公開チャットを運用したことがないんですが、この辺りになるのかな...
https://github.com/rauchg/slackin

あまりこだわりはないので、みなさんのお好きな方でよいかと思います。

**Comment by kskktk** [comment]
いろいろ考えた結果、昨日slackって言っちゃったのでslackにしました。https://aozorahack.slack.comです。

**Comment by cognitom** [comment]
:+1:

**Comment by cognitom** [comment]
あ、スミマセン、どうやって参加すればよいでしょうか?

**Comment by key-amb** [comment]
#kosakuin チャンネル作っておこうかなと思います。
たぶん invite してもらわないと駄目ですよね。
@kskktk さんにメールで依頼を送ってみました。

**Comment by kskktk** [comment]
取り急ぎ @key-amb さんはメールを頂いたので招待しました。その他どのように告知すればいいですかね。僕にメールを送ってもらうようにすればいいのかな。

**Comment by kskktk** [comment]
取り急ぎreadme.mdに告知をいれてみました

**Comment by cognitom** [comment]
公開にはできないでしょうか?

**Comment by kskktk** [comment]
slackって公開設定ってどこでやればいいんでしょうか？ お手数ですが教えてください。僕には「invitation only」か「Any email address from these domains」という設定しかないよう見えるんです……。

**Comment by cognitom** [comment]
すみません、私もSlackはあまり詳しくなくて。Slackinを使っているケースはあるように思いますが、Slack自体が公開が前提のサービスではないような気もしてきました (汗)
https://github.com/rauchg/slackin

**Comment by kskktk** [comment]
どうもそうみたいですね。herokuを使って登録を自動化することはできそうですね。ちょっとやってみましょうか。一旦issueをreopenしますね。

**Comment by kskktk** [comment]
slackinをつかって https://aozorahackinvitation.herokuapp.com/ から自動で登録いただけるようにしました。readme.mdにも追記しました。これでよかったらcloseしましょう。

**Comment by cognitom** [comment]
:+1: バッチリだと思います。ありがとうございます! お手間かけました m(_ _)m
